Repository Plant-for-the-Planet-org/planet-webapp, pull requests merged in 2020-08, with the labels that each got.

#80 Fix: re-enable sticky topbar
  src/features/common/Navbar/Navbar.module.scss
Labels: bug

#79 Create Donation
  src/features/common/Footer/SelectLanguageAndCountry.tsx
  src/features/common/InputTypes/GreenRadio.tsx
  src/features/common/InputTypes/ToggleSwitch.tsx
  src/features/public/Donations/components/PaymentRequestForm.js
  src/features/public/Donations/components/treeDonation/GiftForm.tsx
  src/features/public/Donations/components/treeDonation/PaymentFunctions.ts
  src/features/public/Donations/components/treeDonation/SelectCurrencyModal.tsx
  src/features/public/Donations/components/treeDonation/SelectTaxDeductionCountryModal.tsx
  src/features/public/Donations/screens/TreeDonation.tsx
  src/utils/stripeHelpers.ts
Labels: enhancement

#76 New Image slider on project page
  package-lock.json
  package.json
  src/features/public/Donations/components/ImageSlider.js
  src/features/public/Donations/components/SingleProjectDetails.tsx
  src/features/public/Donations/components/projectDetails/ProjectContactDetails.tsx
  src/features/public/Donations/screens/ProjectDetails.tsx
  src/features/public/Donations/styles/ProjectDetails.module.scss
Labels: Priority, enhancement
