Repository Plant-for-the-Planet-org/planet-webapp, pull requests merged in 2022-06, with the labels that each got.

#1497 fix the issue of picture of a sample tree does not change
  src/features/projects/components/projectDetails/ImageSlider.tsx
Labels: PR: reviewed-approved

#1506 added validation to myspecies
  public/static/locales/en/treemapper.json
  src/features/user/TreeMapper/Import/components/SpeciesAutoComplete.tsx
  src/features/user/TreeMapper/MySpecies.module.scss
  src/features/user/TreeMapper/MySpecies.tsx
Labels: PR: reviewed-approved

#1494 fix the formatting of siteOwnerShip for single project view
  public/static/locales/de/manageProjects.json
  public/static/locales/en/manageProjects.json
  src/features/projects/components/projectDetails/ProjectInfo.tsx
Labels: PR: partially-approved

#1508 don't do the browser check for Safari on Android devices
  src/utils/browsercheck.ts
Labels: PR: reviewed-approved

#1515 fix Heroku build
  .npmrc
  package.json
Labels: PR: unreviewed

#1516 converted decimal to integer in salesforce tenant page
  src/tenants/salesforce/TreeCounter/TreeCounter.tsx
Labels: PR: reviewed-approved

#1507 Integrate updated subscription API
  public/static/locales/en/me.json
  src/features/user/Account/components/RecurrencyRecord.tsx
  src/features/user/Account/payments.d.ts
Labels: PR: reviewed-approved
