Repository Plant-for-the-Planet-org/planet-webapp, pull requests merged in 2022-09, with the labels that each got.

#1553 Bugfix/complete signup
  src/features/common/InputTypes/AutoCompleteCountry.tsx
  src/features/user/CompleteSignup/CompleteSignup.module.scss
  src/features/user/CompleteSignup/index.tsx
  src/theme/global.scss
Labels: PR: reviewed-approved

#1518 Feature/profile donation link
  pages/profile/donation-link.tsx
  public/static/locales/en/country.json
  public/static/locales/en/donationLink.json
  public/static/locales/en/me.json
  src/features/common/InputTypes/AutoCompleteCountryNew.tsx
  src/features/common/InputTypes/MuiAutoComplete.tsx
  src/features/common/Layout/DashboardView/SingleColumnView.tsx
  src/features/common/Layout/Forms/InlineFormDisplayGroup.tsx
  src/features/common/Layout/UserLayout/UserLayout.tsx
  src/features/common/types/countries.d.ts
  src/features/common/types/project.d.ts
  src/features/user/BulkCodes/components/ProjectSelectAutocomplete.tsx
  src/features/user/Widget/DonationLink/CustomSnackbar.tsx
  src/features/user/Widget/DonationLink/DonationLinkForm.module.scss
  src/features/user/Widget/DonationLink/DonationLinkForm.tsx
  src/features/user/Widget/DonationLink/index.tsx
  src/utils/constants/countries.ts
Labels: PR: reviewed-approved

#1556 Feature/planet cash dashboard section
  pages/_app.tsx
  pages/profile/planetcash/index.tsx
  pages/profile/planetcash/new.tsx
  pages/profile/planetcash/transactions.tsx
  public/assets/images/icons/AccountListLoader.tsx
  public/assets/images/icons/Sidebar/PlanetCashIcon.tsx
  public/static/locales/en/common.json
  public/static/locales/en/me.json
  public/static/locales/en/planetcash.json
  src/features/common/InputTypes/AutoCompleteCountryNew.tsx
  src/features/common/Layout/CenteredContainer/index.tsx
  src/features/common/Layout/PlanetCashContext.tsx
  src/features/common/Layout/StyledForm/index.tsx
  src/features/common/Layout/TabbedView/TabSteps.tsx
  src/features/common/Layout/TabbedView/TabbedViewTypes.d.ts
  src/features/common/Layout/TabbedView/index.tsx
  src/features/common/Layout/UserLayout/UserLayout.tsx
  src/features/common/types/country.d.ts
  src/features/common/types/planetcash.d.ts
  src/features/user/Account/AccountHistory.module.scss
  src/features/user/Account/History.tsx
  src/features/user/Account/components/AccountRecord.tsx
  src/features/user/BulkCodes/forms/IssueCodesForm.tsx
  src/features/user/PlanetCash/components/AccountDetails.tsx
  src/features/user/PlanetCash/components/CreateAccountForm.tsx
  src/features/user/PlanetCash/components/NoPlanetCashAccount.tsx
  src/features/user/PlanetCash/components/NoTransactionsFound.tsx
  src/features/user/PlanetCash/index.tsx
  src/features/user/PlanetCash/screens/Accounts.tsx
  src/features/user/PlanetCash/screens/CreateAccount.tsx
  src/features/user/PlanetCash/screens/Transactions.tsx
  src/theme/muiThemeNew.ts
  src/utils/apiRequests/api.ts
  src/utils/constants/countries.ts
Labels: PR: unreviewed

#1567 Add beta tag for Bulk Codes submenu
  src/features/common/Layout/UserLayout/UserLayout.module.scss
  src/features/common/Layout/UserLayout/UserLayout.tsx
Labels: PR: reviewed-approved

#1563 New Message and Error for Delete Profile
  public/static/locales/en/common.json
  src/features/common/Layout/CustomModal/CustomModal.module.scss
  src/features/common/Layout/CustomModal/index.tsx
  src/features/user/Settings/DeleteProfile.tsx
  src/utils/apiRequests/api.ts
Labels: PR: reviewed-approved

#1565 Fix Active button colour for all MUI Date Pickers
  src/features/user/Account/CancelModal.tsx
  src/features/user/Account/EditModal.tsx
  src/features/user/Account/PauseModal.tsx
  src/features/user/ManageProjects/components/DetailedAnalysis.tsx
  src/features/user/ManageProjects/components/ProjectCertificates.tsx
  src/features/user/ManageProjects/components/ProjectSpending.tsx
  src/features/user/RegisterTrees/RegisterTrees.tsx
  src/features/user/TreeMapper/Import/components/PlantingLocation.tsx
  src/features/user/TreeMapper/Import/components/SampleTreeCard.tsx
Labels: PR: reviewed-approved

#1569 add "new" tag for profile donation link
  public/static/locales/de/donate.json
  public/static/locales/en/donate.json
  src/features/common/Layout/UserLayout/UserLayout.tsx
Labels: PR: reviewed-approved

#1564 Makes the toggle Project Details/List button translatable
  public/static/locales/de/maps.json
  public/static/locales/en/maps.json
  src/features/projects/screens/Projects.tsx
  src/features/projects/screens/SingleProjectDetails.tsx
Labels: PR: partially-approved

#1572 fix: removes text transform from MuiButton text
  src/features/common/InputTypes/MuiButton.tsx
Labels: PR: partially-approved

#1571 Updates for Planet Cash
  pages/profile/planetcash/index.tsx
  pages/profile/planetcash/new.tsx
  pages/profile/planetcash/transactions.tsx
  public/static/locales/en/planetcash.json
  src/features/common/Layout/CenteredContainer/index.tsx
  src/features/common/Layout/TabbedView/TabSteps.tsx
  src/features/common/Layout/TabbedView/TabbedViewTypes.d.ts
  src/features/common/Layout/TabbedView/index.tsx
  src/features/user/Account/AccountHistory.module.scss
  src/features/user/PlanetCash/components/AccountDetails.tsx
  src/features/user/PlanetCash/components/CreateAccountForm.tsx
  src/features/user/PlanetCash/components/NoPlanetCashAccount.tsx
  src/features/user/PlanetCash/components/NoTransactionsFound.tsx
  src/features/user/PlanetCash/index.tsx
  src/features/user/PlanetCash/screens/Accounts.tsx
  src/features/user/PlanetCash/screens/CreateAccount.tsx
  src/features/user/PlanetCash/screens/Transactions.tsx
Labels: PR: reviewed-approved

#1576 fix: remove footer app links
  src/features/common/Layout/Footer/index.tsx
Labels: PR: unreviewed

#1577 remove footer app links
  src/features/common/Layout/Footer/index.tsx
Labels: PR: reviewed-approved
