Repository Plant-for-the-Planet-org/planet-webapp, pull requests merged in 2022-03, with the labels that each got.

#1426 add tiktok icon in footer
  src/features/common/Layout/Footer/index.tsx
Labels: PR: reviewed-approved

#1423 refetch projects on language change
  pages/[p].tsx
  pages/index.tsx
  src/features/projects/screens/SingleProjectDetails.tsx
  src/features/user/Profile/ProjectsContainer.tsx
  src/features/user/Profile/index.tsx
Labels: PR: partially-approved

#1429 Trigger redeployment
  README.md
Labels: PR: reviewed-approved

#1430 Remove top project list
  README.md
Labels: PR: reviewed-approved

#1418 navbar moved to top on mobile screens
  src/features/common/LandingVideo/styles.module.scss
  src/features/common/Layout/Footer/Footer.module.scss
  src/features/common/Layout/Navbar/Navbar.scss
  src/features/common/Layout/UserLayout/UserLayout.module.scss
  src/features/projects/styles/ProjectDetails.module.scss
  src/features/projects/styles/Projects.scss
  src/features/projects/styles/ProjectsMap.module.scss
  src/features/projects/styles/VegetationChange.module.scss
  src/tenants/planet/LeaderBoard/components/LeaderBoard.module.scss
  src/theme/global.scss
Labels: PR: unreviewed

#1272 Treemapper Import Web
  package-lock.json
  package.json
  pages/profile/treemapper/import.tsx
  pages/profile/treemapper/index.tsx
  pages/profile/treemapper/my-species.tsx
  public/assets/images/icons/ImportIcon.tsx
  public/assets/images/icons/ThreeDotIcon.tsx
  public/static/locales/de/common.json
  public/static/locales/de/me.json
  public/static/locales/de/treemapper.json
  public/static/locales/en/common.json
  public/static/locales/en/me.json
  public/static/locales/en/treemapper.json
  src/features/common/InputTypes/BootstrapInput.tsx
  src/features/common/InputTypes/MaterialButton.tsx
  src/features/common/Layout/UserLayout/UserLayout.tsx
  src/features/projects/components/projectDetails/PlantSpecies.tsx
  src/features/user/TreeMapper/Import/Import.module.scss
  src/features/user/TreeMapper/Import/components/Map.tsx
  src/features/user/TreeMapper/Import/components/MapComponent.tsx
  src/features/user/TreeMapper/Import/components/PlantingLocation.tsx
  src/features/user/TreeMapper/Import/components/ReviewSubmit.tsx
  src/features/user/TreeMapper/Import/components/SampleTreeCard.tsx
  src/features/user/TreeMapper/Import/components/SampleTrees.tsx
  src/features/user/TreeMapper/Import/components/SpeciesAutoComplete.tsx
  src/features/user/TreeMapper/Import/index.tsx
  src/features/user/TreeMapper/MySpecies.module.scss
  src/features/user/TreeMapper/MySpecies.tsx
  src/features/user/TreeMapper/TreeMapper.module.scss
  src/features/user/TreeMapper/Treemapper.d.ts
  src/features/user/TreeMapper/components/Map.tsx
  src/features/user/TreeMapper/components/PlantLocation.tsx
  src/features/user/TreeMapper/components/PlantLocationPage.tsx
  src/features/user/TreeMapper/index.tsx
  src/theme/global.scss
  src/utils/apiRequests/api.ts
Labels: Priority, PR: unreviewed, PR: reviewed-approved, PR: reviewed-changes-requested

#1435 hide web Import for other than tpo accounts
  src/features/common/Layout/UserLayout/UserLayout.tsx
Labels: PR: reviewed-approved

#1436 fix method of undefined error
  src/features/user/Account/EditModal.tsx
Labels: PR: reviewed-approved

#1444 handled null project name
  src/utils/getTruncatedString.ts
Labels: PR: reviewed-approved

#1446 hotfix project description
  src/utils/getMetaTags/GetProjectMeta.tsx
Labels: PR: reviewed-approved

#1447 handled null description
  src/features/projects/screens/SingleProjectDetails.tsx
Labels: PR: reviewed-approved

#1442 Fix/navlink active
  src/features/common/Layout/UserLayout/UserLayout.tsx
Labels: PR: reviewed-approved

#1428 Remove donations code
  package-lock.json
  package.json
  pages/claim/[type]/[code].tsx
  pages/donation-payment/[code].tsx
  pages/index.tsx
  pages/payment-status.tsx
  public/assets/images/icons/CreditCardIcons/AmexIcon.tsx
  public/assets/images/icons/CreditCardIcons/DinersClub.tsx
  public/assets/images/icons/CreditCardIcons/DiscoverIcon.tsx
  public/assets/images/icons/CreditCardIcons/JcbIcon.tsx
  public/assets/images/icons/CreditCardIcons/Mastercard.tsx
  public/assets/images/icons/CreditCardIcons/StripeIcon.tsx
  public/assets/images/icons/CreditCardIcons/VisaIcon.tsx
  public/assets/images/icons/donation/CreditCard.tsx
  public/assets/images/icons/donation/GiroPay.tsx
  public/assets/images/icons/donation/PaypalIcon.tsx
  public/assets/images/icons/donation/SepaIcon.tsx
  public/assets/images/icons/donation/SofortIcon.tsx
  src/features/common/ShareOptions/ShareOptions.module.scss
  src/features/common/ShareOptions/ShareOptions.tsx
  src/features/donations/components/DirectGift.tsx
  src/features/donations/components/PaymentFunctions.ts
  src/features/donations/components/ShareOptions.tsx
  src/features/donations/components/paymentMethods/CardPayments.tsx
  src/features/donations/components/paymentMethods/GiroPayPayments.tsx
  src/features/donations/components/paymentMethods/PaymentMethodTabs.tsx
  src/features/donations/components/paymentMethods/PaymentRequestCustomButton.tsx
  src/features/donations/components/paymentMethods/Paypal.jsx
  src/features/donations/components/paymentMethods/PaypalPayments.tsx
  src/features/donations/components/paymentMethods/SepaPayments.tsx
  src/features/donations/components/paymentMethods/SofortPayment.tsx
  src/features/donations/components/treeDonation/DirectGift.tsx
  src/features/donations/components/treeDonation/DirectGiftForm.tsx
  src/features/donations/components/treeDonation/GiftForm.tsx
  src/features/donations/components/treeDonation/SelectCurrencyModal.tsx
  src/features/donations/components/treeDonation/SelectTaxDeductionCountryModal.tsx
  src/features/donations/index.tsx
  src/features/donations/legacyDonation.tsx
  src/features/donations/screens/ContactDetails.tsx
  src/features/donations/screens/PaymentDetails.tsx
  src/features/donations/screens/ThankYou.tsx
  src/features/donations/screens/TreeDonation.tsx
  src/features/donations/styles/Donations.module.scss
  src/features/donations/styles/SelectCurrencyModal.module.scss
  src/features/user/Profile/components/RedeemModal.tsx
  src/tenants/salesforce/Home/components/SeaOfTrees.tsx
  src/utils/paypalCurrencies.ts
  src/utils/stripe/getStripe.tsx
  src/utils/stripe/stripeHelpers.tsx
Labels: PR: unreviewed

#1440 add ad space and textual change
  public/static/locales/de/me.json
  src/features/common/Layout/UserLayout/UserLayout.module.scss
  src/features/user/Account/AccountHistory.module.scss
  src/features/user/Account/History.tsx
Labels: PR: unreviewed

#1441 fix:edit modal unfiy size
  src/features/user/Account/AccountHistory.module.scss
  src/features/user/Account/EditModal.tsx
Labels: PR: reviewed-approved

#1458 fixed wrong query string handling
  src/utils/apiRequests/api.ts
Labels: PR: unreviewed

#1459 Release : Fix API Requests
  src/utils/apiRequests/api.ts
Labels: PR: reviewed-approved

#1457 correct giftCertificate i18n key
  public/static/locales/de/me.json
  public/static/locales/en/me.json
  public/static/locales/fr/me.json
  public/static/locales/pt-BR/me.json
Labels: PR: reviewed-approved
