Repository Plant-for-the-Planet-org/planet-webapp, pull requests merged in 2022-08, with the labels that each got.

#1534 fix: update date picker dependencies
  package.json
  src/features/user/Account/CancelModal.tsx
  src/features/user/Account/EditModal.tsx
  src/features/user/Account/PauseModal.tsx
  src/features/user/ManageProjects/components/DetailedAnalysis.tsx
  src/features/user/ManageProjects/components/ProjectCertificates.tsx
  src/features/user/ManageProjects/components/ProjectSpending.tsx
  src/features/user/RegisterTrees/RegisterTrees.tsx
  src/features/user/TreeMapper/Import/components/PlantingLocation.tsx
  src/features/user/TreeMapper/Import/components/SampleTreeCard.tsx
Labels: PR: reviewed-approved

#1535 Release of fix for missing date picker
  package.json
  src/features/user/Account/CancelModal.tsx
  src/features/user/Account/EditModal.tsx
  src/features/user/Account/PauseModal.tsx
  src/features/user/ManageProjects/components/DetailedAnalysis.tsx
  src/features/user/ManageProjects/components/ProjectCertificates.tsx
  src/features/user/ManageProjects/components/ProjectSpending.tsx
  src/features/user/RegisterTrees/RegisterTrees.tsx
  src/features/user/TreeMapper/Import/components/PlantingLocation.tsx
  src/features/user/TreeMapper/Import/components/SampleTreeCard.tsx
Labels: PR: reviewed-approved

#1537 Release German Translations for Bulk codes
  public/static/locales/de/bulkCodes.json
  public/static/locales/de/me.json
  public/static/locales/en/bulkCodes.json
  public/static/locales/en/me.json
  public/static/locales/es/bulkCodes.json
  public/static/locales/fr/bulkCodes.json
  public/static/locales/it/bulkCodes.json
  public/static/locales/pt-BR/bulkCodes.json
Labels: PR: reviewed-approved

#1527 update font for webapp
  public/tenants/culchacandela/config.ts
  public/tenants/energizer/config.ts
  public/tenants/interactClub/config.ts
  public/tenants/nitrosb/config.ts
  public/tenants/planet/config.ts
  public/tenants/planet/configBeta.ts
  public/tenants/senatDerWirtschaft/config.ts
  public/tenants/stern/config.ts
  public/tenants/ttc/config.ts
  public/tenants/ulmpflanzt/config.ts
  public/tenants/xiting/config.ts
  src/features/common/Layout/UserLayout/UserLayout.module.scss
  src/features/projects/styles/ProjectSnippet.module.scss
  src/theme/global.scss
  src/theme/theme.ts
  src/theme/themeProperties.ts
Labels: PR: partially-approved

#1538 feat: update sidebar icon for Bulk Codes
  public/assets/images/icons/Sidebar/GiftIcon.tsx
  src/features/common/Layout/UserLayout/UserLayout.tsx
Labels: PR: unreviewed

#1533 fix: update add planet cash link
  src/features/user/BulkCodes/components/BulkCodesError.tsx
Labels: PR: reviewed-approved

#1526 Widget appears in iframe for private accounts
  src/features/user/Widget/EmbedModal.tsx
Labels: PR: reviewed-approved

#1514 Feature/embed webapp
  pages/_app.tsx
  server.js
  src/features/common/LandingVideo/PlayButton.tsx
  src/features/common/LandingVideo/styles.module.scss
  src/features/common/Layout/Navbar/index.tsx
  src/features/common/Layout/QueryParamsContext.tsx
  src/features/common/Layout/index.tsx
  src/features/projects/components/PopupProject.tsx
  src/features/projects/components/ProjectSnippet.tsx
  src/features/projects/components/ProjectsMap.tsx
  src/features/projects/components/maps/Credits.tsx
  src/features/projects/components/maps/Explore.tsx
  src/features/projects/components/maps/ImageDropdown.tsx
  src/features/projects/components/maps/Markers.tsx
  src/features/projects/components/maps/ProjectTabs.tsx
  src/features/projects/components/maps/SitesDropdown.tsx
  src/features/projects/components/projectDetails/ProjectContactDetails.tsx
  src/features/projects/screens/Projects.tsx
  src/features/projects/screens/SingleProjectDetails.tsx
  src/features/projects/styles/Projects.scss
  src/features/projects/styles/ProjectsMap.module.scss
  src/features/projects/styles/VegetationChange.module.scss
  src/utils/getDonationUrl.ts
  vercel.json
Labels: PR: partially-approved

#1540 Change project list scroll behaviour for embeds + minor update to links
  public/static/locales/en/common.json
  src/features/projects/components/ProjectSnippet.tsx
  src/features/projects/components/maps/Credits.tsx
  src/features/projects/screens/Projects.tsx
  src/features/projects/styles/ProjectDetails.module.scss
  src/features/projects/styles/Projects.scss
Labels: PR: reviewed-approved

#1541 Add locale query param and remove language cookie
  i18n/index.js
  src/features/common/Layout/QueryParamsContext.tsx
Labels: PR: reviewed-approved

#1543 fix: fixes map marker positioning
  src/features/projects/components/maps/Markers.tsx
Labels: PR: reviewed-approved

#1539 Release
  README.md
  i18n/index.js
  pages/_app.tsx
  public/assets/images/icons/Sidebar/GiftIcon.tsx
  public/static/locales/de/bulkCodes.json
  public/static/locales/de/common.json
  public/static/locales/en/common.json
  public/tenants/culchacandela/config.ts
  public/tenants/energizer/config.ts
  public/tenants/interactClub/config.ts
  public/tenants/nitrosb/config.ts
  public/tenants/planet/config.ts
  public/tenants/planet/configBeta.ts
  public/tenants/senatDerWirtschaft/config.ts
  public/tenants/stern/config.ts
  public/tenants/ttc/config.ts
  public/tenants/ulmpflanzt/config.ts
  public/tenants/xiting/config.ts
  server.js
  src/features/common/LandingVideo/PlayButton.tsx
  src/features/common/LandingVideo/styles.module.scss
  src/features/common/Layout/Navbar/index.tsx
  src/features/common/Layout/QueryParamsContext.tsx
  src/features/common/Layout/UserLayout/UserLayout.module.scss
  src/features/common/Layout/UserLayout/UserLayout.tsx
  src/features/common/Layout/index.tsx
  src/features/projects/components/PopupProject.tsx
  src/features/projects/components/ProjectSnippet.tsx
  src/features/projects/components/ProjectsMap.tsx
  src/features/projects/components/maps/Credits.tsx
  src/features/projects/components/maps/Explore.tsx
  src/features/projects/components/maps/ImageDropdown.tsx
  src/features/projects/components/maps/Markers.tsx
  src/features/projects/components/maps/ProjectTabs.tsx
  src/features/projects/components/maps/SitesDropdown.tsx
  src/features/projects/components/projectDetails/ProjectContactDetails.tsx
  src/features/projects/screens/Projects.tsx
  src/features/projects/screens/SingleProjectDetails.tsx
  src/features/projects/styles/ProjectDetails.module.scss
  src/features/projects/styles/ProjectSnippet.module.scss
  src/features/projects/styles/Projects.scss
  src/features/projects/styles/ProjectsMap.module.scss
  src/features/projects/styles/VegetationChange.module.scss
  src/features/user/BulkCodes/components/BulkCodesError.tsx
  src/features/user/Widget/EmbedModal.tsx
  src/theme/global.scss
  src/theme/theme.ts
  src/theme/themeProperties.ts
  src/utils/getDonationUrl.ts
  vercel.json
Labels: PR: reviewed-approved

#1545 fix: remove "Powered by" text from locale files
  public/static/locales/en/common.json
  src/features/projects/components/maps/Credits.tsx
Labels: PR: reviewed-approved

#1548 Minor fixes and updates
  src/features/common/Layout/Navbar/index.tsx
  src/features/user/Account/AccountHistory.module.scss
  src/features/user/Account/History.tsx
Labels: PR: reviewed-approved

#1524 [Snyk] Security upgrade moment from 2.29.3 to 2.29.4
  package-lock.json
  package.json
Labels: PR: unreviewed

#1544 Add new controls for webapp in embedded mode
  src/features/common/InputTypes/MuiButton.tsx
  src/features/common/LandingVideo/PlayButton.tsx
  src/features/common/LandingVideo/styles.module.scss
  src/features/common/Layout/QueryParamsContext.tsx
  src/features/projects/components/maps/ImageDropdown.tsx
  src/features/projects/components/maps/ProjectTabs.tsx
  src/features/projects/components/maps/SitesDropdown.tsx
  src/features/projects/screens/Projects.tsx
  src/features/projects/screens/SingleProjectDetails.tsx
  src/features/projects/styles/ProjectDetails.module.scss
  src/features/projects/styles/Projects.scss
  src/features/projects/styles/ProjectsMap.module.scss
  src/features/projects/styles/VegetationChange.module.scss
Labels: PR: reviewed-approved

#1551 remove extra space for width < 481px
  src/features/common/Layout/UserLayout/UserLayout.module.scss
  src/theme/global.scss
Labels: PR: unreviewed

#1549 Release August 16th, 2022
  package-lock.json
  package.json
  public/static/locales/en/common.json
  src/features/common/InputTypes/MuiButton.tsx
  src/features/common/LandingVideo/PlayButton.tsx
  src/features/common/LandingVideo/styles.module.scss
  src/features/common/Layout/Navbar/index.tsx
  src/features/common/Layout/QueryParamsContext.tsx
  src/features/common/Layout/UserLayout/UserLayout.module.scss
  src/features/projects/components/maps/Credits.tsx
  src/features/projects/components/maps/ImageDropdown.tsx
  src/features/projects/components/maps/ProjectTabs.tsx
  src/features/projects/components/maps/SitesDropdown.tsx
  src/features/projects/screens/Projects.tsx
  src/features/projects/screens/SingleProjectDetails.tsx
  src/features/projects/styles/ProjectDetails.module.scss
  src/features/projects/styles/Projects.scss
  src/features/projects/styles/ProjectsMap.module.scss
  src/features/projects/styles/VegetationChange.module.scss
  src/features/user/Account/AccountHistory.module.scss
  src/features/user/Account/History.tsx
  src/theme/global.scss
Labels: PR: reviewed-approved
