Repository Plant-for-the-Planet-org/planet-webapp, pull requests merged in 2022-05, with the labels that each got.

#1477 Fix/explore single project
  package-lock.json
  src/features/projects/components/projectDetails/ProjectInfo.tsx
  src/features/projects/screens/SingleProjectDetails.tsx
Labels: PR: unreviewed

#1481 fix: remove duplicate main challenge
  src/features/projects/components/projectDetails/ProjectInfo.tsx
Labels: PR: reviewed-approved

#1482 terms and condition locale changes
  public/static/locales/de/editProfile.json
Labels: PR: reviewed-approved

#1488 fix: remove /100 for amounts in payment history
  src/features/user/Account/components/AccountRecord.tsx
Labels: PR: reviewed-approved

#1489 fix the terms and condition missing part
  public/static/locales/de/editProfile.json
  public/static/locales/en/editProfile.json
  src/features/user/CompleteSignup/index.tsx
Labels: PR: partially-approved
