Repository Plant-for-the-Planet-org/planet-webapp, pull requests merged in 2023-08, with the labels that each got.

#1815 Feature/use planet sdk project types
  package-lock.json
  package.json
  pages/[p].tsx
  pages/index.tsx
  src/features/common/Layout/BulkCodeContext.tsx
  src/features/common/Layout/ProjectPropsContext.tsx
  src/features/common/types/ProjectPropsContextInterface.ts
  src/features/common/types/donations.ts
  src/features/common/types/plantLocation.d.ts
  src/features/common/types/project.d.ts
  src/features/donations/components/DirectGift.tsx
  src/features/projects/components/PlantLocation/ImageSlider.tsx
  src/features/projects/components/PlantLocation/PlantLocationDetails.tsx
  src/features/projects/components/PopupProject.tsx
  src/features/projects/components/ProjectSnippet.tsx
  src/features/projects/components/ProjectsMap.tsx
  src/features/projects/components/VerifiedBadge.tsx
  src/features/projects/components/maps/Explore.tsx
  src/features/projects/components/maps/ExploreInfoModal.tsx
  src/features/projects/components/maps/ExploreLayers.tsx
  src/features/projects/components/maps/Home.tsx
  src/features/projects/components/maps/ImageDropdown.tsx
  src/features/projects/components/maps/Location.tsx
  src/features/projects/components/maps/Markers.tsx
  src/features/projects/components/maps/PlantLocations.tsx
  src/features/projects/components/maps/Project.tsx
  src/features/projects/components/maps/ProjectPolygon.tsx
  src/features/projects/components/maps/ProjectTabs.tsx
  src/features/projects/components/maps/SatelliteLayer.tsx
  src/features/projects/components/maps/Sites.tsx
  src/features/projects/components/maps/SitesDropdown.tsx
  src/features/projects/components/maps/TimeTravel.tsx
  src/features/projects/components/projectDetails/CarbonCaptured.tsx
  src/features/projects/components/projectDetails/ImageSlider.tsx
  src/features/projects/components/projectDetails/PlantSpecies.tsx
  src/features/projects/components/projectDetails/ProjectContactDetails.tsx
  src/features/projects/components/projectDetails/ProjectInfo.tsx
  src/features/projects/components/projectDetails/TopProjectReports.tsx
  src/features/projects/components/projects/Filters.tsx
  src/features/projects/components/projects/Header.tsx
  src/features/projects/screens/Projects.tsx
  src/features/projects/screens/SingleProjectDetails.tsx
  src/features/user/Account/History.tsx
  src/features/user/BulkCodes/components/ProjectSelectAutocomplete.tsx
  src/features/user/BulkCodes/components/ProjectSelector.tsx
  src/features/user/BulkCodes/forms/IssueCodesForm.tsx
  src/features/user/BulkCodes/forms/SelectProjectForm.tsx
  src/features/user/BulkCodes/index.tsx
  src/features/user/Profile/ProjectsContainer.tsx
  src/features/user/TreeMapper/Analytics/index.tsx
  src/features/user/TreeMapper/Import/components/PlantingLocation.tsx
  src/features/user/Widget/DonationLink/DonationLinkForm.tsx
  src/features/user/Widget/DonationLink/index.tsx
  src/tenants/salesforce/Home/components/SeaOfTrees.tsx
  src/utils/getMetaTags/GetProjectMeta.tsx
  src/utils/maps/plantLocations.ts
  src/utils/maps/zoomToLocation.ts
  src/utils/maps/zoomToProjectSite.ts
Labels: PR: reviewed-approved

#1836 Fixes Project Form Bug - extra field `ecosystems`
  src/features/user/ManageProjects/ProjectsContainer.tsx
  src/features/user/ManageProjects/components/BasicDetails.tsx
Labels: PR: reviewed-approved

#1827 Remove empty component props
  pages/profile/donation-link.tsx
  pages/profile/giftfund/index.tsx
  pages/profile/history.tsx
  pages/profile/projects/[id].tsx
  pages/profile/projects/index.tsx
  pages/profile/recurrency.tsx
  pages/profile/register-trees.tsx
  pages/profile/treemapper/import.tsx
  pages/profile/treemapper/index.tsx
  pages/profile/treemapper/my-species.tsx
  pages/s/[id].tsx
  pages/verify-email.tsx
  public/assets/images/icons/CopyIcon.tsx
  public/assets/images/icons/ImportIcon.tsx
  public/assets/images/icons/MinusIcon.tsx
  public/assets/images/icons/PlayIcon.tsx
  public/assets/images/icons/PlusIcon.tsx
  public/assets/images/icons/ThreeDotIcon.tsx
  public/assets/images/icons/UnderMaintenance.tsx
  src/features/common/ContentLoaders/Projects/AccessDeniedLoader.tsx
  src/features/common/ContentLoaders/Projects/GlobeLoader.tsx
  src/features/common/ContentLoaders/Projects/ProjectLoader.tsx
  src/features/common/ContentLoaders/Projects/ProjectLoaderDetails.tsx
  src/features/common/Layout/Footer/AccountFooter.tsx
  src/features/common/Layout/UnderMaintenance/index.tsx
  src/features/common/VerifyEmail/VerifyEmail.tsx
  src/features/user/ManageProjects/ProjectsContainer.tsx
  src/features/user/RegisterTrees/RegisterTrees.tsx
  src/features/user/TreeMapper/Import/components/Map.tsx
  src/features/user/TreeMapper/Import/index.tsx
  src/features/user/TreeMapper/MySpecies.tsx
  src/features/user/TreeMapper/index.tsx
  src/tenants/planet/LeaderBoard/components/Stories.tsx
  src/tenants/planet/LeaderBoard/components/Video.tsx
Labels: PR: reviewed-approved, Next in line

#1826 Fix widgets layout
  pages/profile/widgets.tsx
  src/features/common/Layout/UserLayout/UserLayout.module.scss
Labels: PR: reviewed-approved, Next in line

#1816 Resolve codefactor errors (/features/common)
  src/features/common/CopyToClipboard/index.tsx
  src/features/common/InputTypes/AnimatedButton.tsx
  src/features/common/InputTypes/AutoCompleteCountry.tsx
  src/features/common/InputTypes/MaterialButton.tsx
  src/features/common/InputTypes/ToggleSwitch.tsx
  src/features/common/LandingVideo/PlayButton.tsx
  src/features/common/Layout/CookiePolicy/index.tsx
  src/features/common/Layout/DarkModeSwitch.tsx/index.tsx
  src/features/common/Layout/ErrorPopup/index.tsx
  src/features/common/Layout/Footer/AccountFooter.tsx
  src/features/common/Layout/Footer/SelectLanguageAndCountry.tsx
  src/features/common/Layout/Footer/index.tsx
  src/features/common/Layout/Header/index.tsx
  src/features/common/Layout/Navbar/getNavBarIcon.tsx
  src/features/common/Layout/Navbar/getSubMenu.tsx
  src/features/common/Layout/Navbar/index.tsx
  src/features/common/Layout/RedeemPopup/index.tsx
  src/features/common/Layout/SingleColumnView/index.tsx
  src/features/common/Layout/TabbedView/index.tsx
  src/features/common/Layout/UserLayout/UserLayout.tsx
  src/features/common/Layout/index.tsx
  src/features/common/ShareOptions/ShareOptions.module.scss
  src/features/common/ShareOptions/ShareOptions.tsx
  src/features/common/TreeCounter/TreeCounter.tsx
  src/features/common/VerifyEmail/VerifyEmail.tsx
  src/features/common/types/commonConfig.d.ts
  src/features/common/types/payments.d.ts
  src/features/common/types/project.d.ts
Labels: PR: reviewed-approved, Next in line

#1704 refactor: project creation
  package-lock.json
  package.json
  pages/profile/projects/[id].tsx
  pages/profile/projects/new-project.tsx
  public/assets/images/icons/manageProjects/Star.tsx
  public/static/locales/en/manageProjects.json
  src/features/common/Layout/Forms/InlineFormDisplayGroup.tsx
  src/features/common/Layout/TabbedView/index.tsx
  src/features/common/types/project.d.ts
  src/features/projects/styles/Projects.scss
  src/features/user/ManageProjects/StepForm.module.scss
  src/features/user/ManageProjects/components/BasicDetails.tsx
  src/features/user/ManageProjects/components/DetailedAnalysis.tsx
  src/features/user/ManageProjects/components/ProjectCertificates.tsx
  src/features/user/ManageProjects/components/ProjectMedia.tsx
  src/features/user/ManageProjects/components/ProjectSelection.tsx
  src/features/user/ManageProjects/components/ProjectSites.tsx
  src/features/user/ManageProjects/components/ProjectSpending.tsx
  src/features/user/ManageProjects/components/SubmitForReview.tsx
  src/features/user/ManageProjects/index.tsx
  src/theme/global.scss
  src/theme/themeStyles.ts
Labels: PR: reviewed-approved, Next in line

#1840 use some existing label for projects on profile page
  public/static/locales/de/donate.json
  public/static/locales/en/donate.json
  public/static/locales/es/donate.json
  public/static/locales/fr/donate.json
  public/static/locales/it/donate.json
  public/static/locales/pt-BR/donate.json
  src/features/user/Profile/ProjectsContainer.tsx
Labels: bug

#1833 Displays new project properties (map/project details)
  package-lock.json
  package.json
  public/static/locales/en/common.json
  public/static/locales/en/manageProjects.json
  src/features/projects/components/PopupProject.tsx
  src/features/projects/components/ProjectSnippet.tsx
  src/features/projects/components/projectDetails/ProjectInfo.tsx
  src/features/projects/styles/ProjectSnippet.module.scss
  src/features/user/ManageProjects/components/DetailedAnalysis.tsx
Labels: Next in line

#1839 Updates Manage Projects with new properties
  package-lock.json
  package.json
  public/static/locales/cs/manageProjects.json
  public/static/locales/de/manageProjects.json
  public/static/locales/en/manageProjects.json
  public/static/locales/es/manageProjects.json
  public/static/locales/fr/manageProjects.json
  public/static/locales/it/manageProjects.json
  public/static/locales/pt-BR/manageProjects.json
  src/features/common/types/project.d.ts
  src/features/user/ManageProjects/StepForm.module.scss
  src/features/user/ManageProjects/components/BasicDetails.tsx
  src/features/user/ManageProjects/components/DetailedAnalysis.tsx
  src/features/user/ManageProjects/index.tsx
Labels: Next in line

#1843 Release All-Methods Projects
  package-lock.json
  package.json
  pages/profile/projects/[id].tsx
  pages/profile/projects/new-project.tsx
  public/assets/images/icons/manageProjects/Star.tsx
  public/static/locales/cs/manageProjects.json
  public/static/locales/de/donate.json
  public/static/locales/de/manageProjects.json
  public/static/locales/en/common.json
  public/static/locales/en/donate.json
  public/static/locales/en/manageProjects.json
  public/static/locales/es/donate.json
  public/static/locales/es/manageProjects.json
  public/static/locales/fr/donate.json
  public/static/locales/fr/manageProjects.json
  public/static/locales/it/donate.json
  public/static/locales/it/manageProjects.json
  public/static/locales/pt-BR/donate.json
  public/static/locales/pt-BR/manageProjects.json
  src/features/common/Layout/Forms/InlineFormDisplayGroup.tsx
  src/features/common/Layout/TabbedView/index.tsx
  src/features/common/types/project.d.ts
  src/features/projects/components/PopupProject.tsx
  src/features/projects/components/ProjectSnippet.tsx
  src/features/projects/components/projectDetails/ProjectInfo.tsx
  src/features/projects/styles/ProjectSnippet.module.scss
  src/features/projects/styles/Projects.scss
  src/features/user/ManageProjects/StepForm.module.scss
  src/features/user/ManageProjects/components/BasicDetails.tsx
  src/features/user/ManageProjects/components/DetailedAnalysis.tsx
  src/features/user/ManageProjects/components/ProjectCertificates.tsx
  src/features/user/ManageProjects/components/ProjectMedia.tsx
  src/features/user/ManageProjects/components/ProjectSelection.tsx
  src/features/user/ManageProjects/components/ProjectSites.tsx
  src/features/user/ManageProjects/components/ProjectSpending.tsx
  src/features/user/ManageProjects/components/SubmitForReview.tsx
  src/features/user/ManageProjects/index.tsx
  src/features/user/Profile/ProjectsContainer.tsx
  src/theme/global.scss
  src/theme/themeStyles.ts
Labels: PR: reviewed-approved

#1739 Component unification (Register Trees)
  pages/profile/register-trees.tsx
  src/features/user/RegisterTrees/RegisterModal.module.scss
  src/features/user/RegisterTrees/RegisterTrees/SingleContribution.tsx
  src/features/user/RegisterTrees/RegisterTrees/UploadImages.tsx
  src/features/user/RegisterTrees/RegisterTreesForm.tsx
  src/features/user/RegisterTrees/index.tsx
Labels: PR: reviewed-approved

#1831 Component Unification (Import Data)
  src/features/user/TreeMapper/Import/Import.module.scss
  src/features/user/TreeMapper/Import/components/PlantingLocation.tsx
  src/features/user/TreeMapper/Import/components/ReviewSubmit.tsx
  src/features/user/TreeMapper/Import/components/SampleTreeCard.tsx
  src/features/user/TreeMapper/Import/components/SampleTrees.tsx
  src/features/user/TreeMapper/Import/index.tsx
Labels: PR: reviewed-approved

#1832 Component Unification (recurrency)
  pages/profile/recurrency.tsx
  src/features/user/Account/Recurrency.tsx
  src/features/user/Account/RecurrentPayments.tsx
  src/features/user/Account/components/RecurrencyRecord.tsx
Labels: PR: reviewed-approved

#1837 Component Unification (History)
  src/features/user/Account/AccountHistory.module.scss
  src/features/user/Account/History.tsx
Labels: PR: reviewed-approved

#1841 Hotfix/remove impersonation data
  src/features/common/Layout/UserPropsContext.tsx
Labels: PR: reviewed-approved

#1852 remove Android/iOS well-known files for app support and app redirects
  netlify.toml
  next.config.js
  pages/open-app.tsx
  public/.well-known/apple-app-site-association
  public/.well-known/assetlinks.json
  public/_redirects
  public/static/locales/cs/common.json
  public/static/locales/de/common.json
  public/static/locales/en/common.json
  public/static/locales/es/common.json
  public/static/locales/fr/common.json
  public/static/locales/it/common.json
  public/static/locales/pt-BR/common.json
Labels: PR: reviewed-approved
