Repository Plant-for-the-Planet-org/planet-webapp, pull requests merged in 2023-02, with the labels that each got.

#1671 Release MUI changes (Feb 2nd, 2023)
  .storybook/preview.js
  package.json
  src/features/common/InputTypes/MuiButton.tsx
  src/features/common/Layout/DashboardView/index.tsx
  src/features/user/Account/EditModal.tsx
  src/features/user/ManageProjects/components/DetailedAnalysis.tsx
  src/features/user/ManageProjects/components/ProjectCertificates.tsx
  src/features/user/ManageProjects/components/ProjectSpending.tsx
  src/features/user/RegisterTrees/RegisterTrees.tsx
  src/features/user/TreeMapper/Import/components/PlantingLocation.tsx
  src/features/user/TreeMapper/Import/components/SampleTreeCard.tsx
  src/theme/muiThemeNew.ts
  src/theme/themeProperties.ts
  src/theme/themeStyles.ts
Labels: PR: reviewed-approved

#1681 Minor Release: Upgrade MUI
  package.json
Labels: PR: reviewed-approved

#1642 [Snyk] Upgrade react-map-gl from 5.3.19 to 5.3.20
  package-lock.json
  package.json
Labels: dependencies, PR: reviewed-approved

#1616 Rework detail screen for sample trees in RO profile
  public/static/locales/en/treemapper.json
  src/features/user/TreeMapper/TreeMapper.module.scss
  src/features/user/TreeMapper/components/PlantLocationPage.tsx
Labels: PR: unreviewed

#1623 Display remeasurement images
  src/features/user/TreeMapper/components/PlantLocationPage.tsx
Labels: PR: unreviewed

#1621 Feature/donation link qr code
  package-lock.json
  package.json
  pages/[p].tsx
  public/static/locales/en/donationLink.json
  src/features/user/Widget/DonationLink/DonationLinkForm.module.scss
  src/features/user/Widget/DonationLink/DonationLinkForm.tsx
  src/features/user/Widget/DonationLink/index.tsx
  src/utils/apiRequests/api.ts
Labels: PR: unreviewed

#1676 Add partner signup info for planet cash / bulk codes
  public/static/locales/en/bulkCodes.json
  public/static/locales/en/planetcash.json
  src/features/user/BulkCodes/index.tsx
  src/features/user/PlanetCash/index.tsx
Labels: PR: unreviewed

#1680 fix: restricted double click of redeem code button
  src/features/user/Profile/components/RedeemModal.tsx
Labels: PR: reviewed-approved

#1679 fix:restrict access to page for unauthorize user
  pages/profile/payouts/add-bank-details.tsx
  pages/profile/payouts/index.tsx
  pages/profile/payouts/schedule.tsx
  pages/profile/projects/index.tsx
  pages/profile/projects/new-project.tsx
  pages/profile/treemapper/import.tsx
  pages/profile/treemapper/my-species.tsx
Labels: PR: reviewed-approved

#1574 Implement Re-measurement data in the frontend
  public/static/locales/en/maps.json
  src/features/projects/components/PlantLocation/PlantLocationDetails.tsx
Labels: PR: unreviewed

#1661 Gift Funds Cleanup
  src/features/common/Layout/SingleColumnView/index.tsx
  src/features/common/types/user.d.ts
  src/features/user/GiftFunds/Details.tsx
  src/features/user/GiftFunds/GiftFundDetails.tsx
  src/features/user/GiftFunds/GiftFunds.module.scss
  src/features/user/GiftFunds/index.tsx
  src/features/user/Widget/DonationLink/index.tsx
Labels: PR: reviewed-approved

#1691 Fix minor issues with release
  package-lock.json
  package.json
  src/features/user/PlanetCash/index.tsx
Labels: PR: reviewed-approved

#1692 Remove inline styles form donation link QR code
  src/features/user/Widget/DonationLink/DonationLinkForm.module.scss
  src/features/user/Widget/DonationLink/DonationLinkForm.tsx
Labels: PR: reviewed-approved
