Repository Plant-for-the-Planet-org/planet-webapp, pull requests merged in 2023-05, with the labels that each got.

#1737 feat: allow czech language for selective tenants
  public/tenants/planet/config.ts
  public/tenants/ttc/config.ts
  src/utils/language/supportedLanguages.json
Labels: PR: reviewed-approved

#1685 Allow expandable details for offline (incomplete) subscriptions
  pages/profile/history.tsx
  pages/profile/recurrency.tsx
  public/static/locales/en/me.json
  src/features/common/types/payments.d.ts
  src/features/user/Account/AccountHistory.module.scss
  src/features/user/Account/CancelModal.tsx
  src/features/user/Account/EditModal.tsx
  src/features/user/Account/History.tsx
  src/features/user/Account/PauseModal.tsx
  src/features/user/Account/ReactivateModal.tsx
  src/features/user/Account/Recurrency.tsx
  src/features/user/Account/components/AccountRecord.tsx
  src/features/user/Account/components/RecurrencyRecord.tsx
  src/features/user/Account/components/TransferDetails.tsx
  src/features/user/Account/payments.d.ts
  src/features/user/PlanetCash/screens/Transactions.tsx
Labels: PR: reviewed-approved

#1763 Fixes the complete signup loop bug
  src/features/common/Layout/UserPropsContext.tsx
Labels: PR: partially-approved

#1764 Release Fix Signup Loop
  src/features/common/Layout/UserPropsContext.tsx
Labels: PR: partially-approved

#1762 [Snyk] Upgrade react-map-gl from 5.3.20 to 5.3.21
  package-lock.json
  package.json
Labels: dependencies, PR: reviewed-approved

#1666 feature/home logo
  public/assets/images/navigation/HomeLogoSelected.tsx
  public/assets/images/navigation/HomoLogo.tsx
  public/tenants/planet/config.ts
  src/features/common/Layout/Navbar/Navbar.scss
  src/features/common/Layout/Navbar/getNavBarIcon.tsx
  src/features/common/Layout/Navbar/index.tsx
Labels: PR: reviewed-approved, Next in line

#1769 Adds enable_intro query param to enable intro video for embedded site
  pages/_app.tsx
  src/features/common/LandingVideo/PlayButton.tsx
  src/features/common/LandingVideo/index.tsx
  src/features/common/Layout/QueryParamsContext.tsx
Labels: PR: reviewed-approved

#1767 Release May II
  package-lock.json
  package.json
  pages/_app.tsx
  pages/claim/[type]/[code].tsx
  pages/profile/delete-account.tsx
  pages/profile/redeem/[code].tsx
  public/assets/images/navigation/HomeLogoSelected.tsx
  public/assets/images/navigation/HomoLogo.tsx
  public/static/locales/cs/common.json
  public/static/locales/cs/donate.json
  public/static/locales/de/redeem.json
  public/static/locales/en/redeem.json
  public/tenants/planet/config.ts
  src/features/common/LandingVideo/PlayButton.tsx
  src/features/common/LandingVideo/index.tsx
  src/features/common/Layout/Navbar/Navbar.scss
  src/features/common/Layout/Navbar/getNavBarIcon.tsx
  src/features/common/Layout/Navbar/index.tsx
  src/features/common/Layout/QueryParamsContext.tsx
  src/features/common/RedeemCode/EnterRedeemCode.tsx
  src/features/common/RedeemCode/RedeemFailed.tsx
  src/features/common/RedeemCode/SuccessfullyRedeemed.tsx
  src/features/common/RedeemCode/index.tsx
  src/features/common/RedeemMicro/RedeemCode.tsx
  src/features/user/Profile/components/RedeemModal.tsx
  src/features/user/Profile/styles/RedeemModal.module.scss
  src/features/user/Settings/DeleteProfile.module.scss
  src/features/user/Settings/DeleteProfile/DeleteProfile.module.scss
  src/features/user/Settings/DeleteProfile/DeleteProfileForm.tsx
  src/features/user/Settings/DeleteProfile/index.tsx
  src/theme/themeStyles.ts
Labels: PR: unreviewed

#1772 fix: login issue using direct link
  pages/login.tsx
Labels: PR: reviewed-approved

#1669 fix:disable donor certificate for conservation project
  src/features/user/Account/components/AccountRecord.tsx
  src/features/user/Account/components/Certificates.tsx
Labels: PR: reviewed-approved

#1733 Component unification (Api Key page)
  pages/profile/api-key.tsx
  src/features/user/Settings/ApiKey.module.scss
  src/features/user/Settings/ApiKey.tsx
  src/features/user/Settings/ApiKey/ApiKey.module.scss
  src/features/user/Settings/ApiKey/ApiKeyForm.tsx
  src/features/user/Settings/ApiKey/index.tsx
Labels: PR: reviewed-approved

#1746 fix: double calling redeemcode function
  pages/claim/[type]/[code].tsx
  pages/profile/redeem/[code].tsx
  src/features/common/RedeemMicro/RedeemCode.tsx
Labels: PR: reviewed-approved

#1773 Sign up button multiple clicks
  src/features/user/CompleteSignup/index.tsx
Labels: PR: reviewed-approved

#1777 Release May III
  pages/claim/[type]/[code].tsx
  pages/profile/api-key.tsx
  pages/profile/redeem/[code].tsx
  src/features/common/RedeemCode/EnterRedeemCode.tsx
  src/features/common/RedeemCode/RedeemFailed.tsx
  src/features/user/Account/components/AccountRecord.tsx
  src/features/user/Account/components/Certificates.tsx
  src/features/user/CompleteSignup/index.tsx
  src/features/user/Profile/components/RedeemModal.tsx
  src/features/user/Settings/ApiKey.module.scss
  src/features/user/Settings/ApiKey.tsx
  src/features/user/Settings/ApiKey/ApiKey.module.scss
  src/features/user/Settings/ApiKey/ApiKeyForm.tsx
  src/features/user/Settings/ApiKey/index.tsx
Labels: PR: reviewed-approved

#1784 [Snyk] Upgrade sass from 1.62.0 to 1.62.1
  package-lock.json
  package.json
Labels: dependencies, PR: reviewed-approved

#1781 Update blue carbon project link for salesforce
  src/tenants/salesforce/Home/components/SeaOfTrees.tsx
Labels: PR: reviewed-approved

#1786 Updates node version and package-lock after dep updates
  package-lock.json
  package.json
Labels: PR: reviewed-approved

#1774 Modifications to Top/Verified projects
  public/assets/images/icons/project/TopProjectIcon.tsx
  public/static/locales/en/common.json
  src/features/projects/components/PopupProject.tsx
  src/features/projects/components/ProjectSnippet.tsx
  src/features/projects/components/TopProjectBadge.tsx
  src/features/projects/components/VerifiedBadge.tsx
  src/features/projects/styles/ProjectSnippet.module.scss
Labels: PR: reviewed-changes-requested

#1790 Release Cleanup - May IV
  src/features/projects/components/ProjectSnippet.tsx
Labels: PR: unreviewed

#1785 Release May IV
  package-lock.json
  package.json
  pages/api/data-explorer/export.ts
  pages/api/data-explorer/species-planted.ts
  pages/api/data-explorer/total-species-planted.ts
  pages/api/data-explorer/total-trees-planted.ts
  pages/api/data-explorer/trees-planted.ts
  public/assets/images/icons/project/TopProjectIcon.tsx
  public/static/locales/en/common.json
  public/static/locales/en/treemapperAnalytics.json
  src/features/common/types/dataExplorer.d.ts
  src/features/projects/components/PopupProject.tsx
  src/features/projects/components/ProjectSnippet.tsx
  src/features/projects/components/TopProjectBadge.tsx
  src/features/projects/components/VerifiedBadge.tsx
  src/features/projects/styles/ProjectSnippet.module.scss
  src/features/user/TreeMapper/Analytics/components/Counter/index.tsx
  src/features/user/TreeMapper/Analytics/components/Export/index.tsx
  src/features/user/TreeMapper/Analytics/components/SpeciesPlanted/index.tsx
  src/features/user/TreeMapper/Analytics/components/TreePlanted/index.tsx
  src/hooks/use-next-request.ts
  src/middlewares/rate-limiter.ts
  src/tenants/salesforce/Home/components/SeaOfTrees.tsx
Labels: PR: reviewed-approved
