Repository Plant-for-the-Planet-org/planet-webapp, pull requests merged in 2023-11, with the labels that each got.

#1795 Add project type icons
  public/assets/images/icons/project/Agroforestry.tsx
  public/assets/images/icons/project/Conservation.tsx
  public/assets/images/icons/project/ManagedRegeneration.tsx
  public/assets/images/icons/project/Mangroves.tsx
  public/assets/images/icons/project/NaturalRegeneration.tsx
  public/assets/images/icons/project/TreePlanting.tsx
  public/assets/images/icons/project/UrbanRestoration.tsx
  src/features/projects/components/PopupProject.tsx
  src/features/projects/components/ProjectSnippet.tsx
  src/features/projects/components/ProjectTypeIcon.tsx
  src/features/projects/components/maps/Markers.tsx
  src/features/projects/styles/ProjectSnippet.module.scss
  src/features/projects/styles/ProjectsMap.module.scss
Labels: PR: reviewed-approved, blocked

#1794 Feature/update background color
  public/assets/images/icons/project/ProjectInfo.tsx
  public/static/locales/en/common.json
  src/features/projects/components/PopupProject.tsx
  src/features/projects/components/ProjectSnippet.tsx
  src/features/projects/components/TopProjectBadge.tsx
  src/features/projects/styles/ProjectDetails.module.scss
  src/features/projects/styles/ProjectSnippet.module.scss
  src/theme/_colors.scss
  src/theme/theme.ts
  src/theme/themeProperties.ts
Labels: PR: unreviewed

#1919 update top project badge color
  src/features/projects/styles/ProjectSnippet.module.scss
  src/theme/themeProperties.ts
Labels: PR: reviewed-approved

#1917 Release November I
  public/assets/images/icons/project/Agroforestry.tsx
  public/assets/images/icons/project/Conservation.tsx
  public/assets/images/icons/project/ManagedRegeneration.tsx
  public/assets/images/icons/project/Mangroves.tsx
  public/assets/images/icons/project/NaturalRegeneration.tsx
  public/assets/images/icons/project/ProjectInfo.tsx
  public/assets/images/icons/project/TreePlanting.tsx
  public/assets/images/icons/project/UrbanRestoration.tsx
  public/static/locales/en/common.json
  public/static/locales/es/common.json
  public/static/locales/fr/common.json
  public/static/locales/it/common.json
  public/static/locales/pt-BR/common.json
  src/features/projects/components/PopupProject.tsx
  src/features/projects/components/ProjectSnippet.tsx
  src/features/projects/components/ProjectTypeIcon.tsx
  src/features/projects/components/TopProjectBadge.tsx
  src/features/projects/components/maps/Markers.tsx
  src/features/projects/styles/ProjectDetails.module.scss
  src/features/projects/styles/ProjectSnippet.module.scss
  src/features/projects/styles/ProjectsMap.module.scss
  src/theme/_colors.scss
  src/theme/theme.ts
  src/theme/themeProperties.ts
Labels: PR: unreviewed

#1899 Resolve codefactor errors
  src/features/common/InputTypes/AutoCompleteCountry.tsx
  src/features/common/Layout/Footer/index.tsx
  src/features/common/Layout/index.tsx
  src/features/common/types/country.d.ts
  src/features/projects/components/ProjectSnippet.tsx
  src/features/projects/components/ProjectsMap.tsx
  src/features/projects/components/projects/SearchBar.tsx
  src/features/user/CompleteSignup/index.tsx
  src/features/user/PlanetCash/components/CreateAccountForm.tsx
  src/features/user/Settings/EditProfile/EditProfileForm.tsx
  src/features/user/Widget/DonationLink/DonationLinkForm.tsx
  src/tenants/common/Home/index.tsx
  src/tenants/common/LeaderBoard/index.tsx
  src/tenants/planet/LeaderBoard/index.tsx
  src/tenants/salesforce/Home/index.tsx
  src/tenants/stern/Home/index.tsx
  tenant.config.ts
Labels: PR: reviewed-approved

#1920 Updates profile validation
  .babelrc
  package-lock.json
  package.json
  pages/complete-signup.tsx
  pages/profile/edit.tsx
  public/static/locales/cs/editProfile.json
  public/static/locales/de/editProfile.json
  public/static/locales/en/editProfile.json
  public/static/locales/es/editProfile.json
  public/static/locales/fr/editProfile.json
  public/static/locales/it/editProfile.json
  public/static/locales/pt-BR/editProfile.json
  src/features/user/CompleteSignup/index.tsx
  src/features/user/Settings/EditProfile/EditProfileForm.tsx
Labels: PR: reviewed-approved

#1925 Conservation project icon addition
  src/features/projects/components/PopupProject.tsx
  src/features/projects/components/ProjectSnippet.tsx
  src/features/projects/styles/ProjectSnippet.module.scss
Labels: PR: reviewed-approved

#1924 Release November II
  .babelrc
  package-lock.json
  package.json
  pages/complete-signup.tsx
  pages/profile/edit.tsx
  public/assets/images/icons/project/UrbanRestoration.tsx
  public/static/locales/cs/editProfile.json
  public/static/locales/de/common.json
  public/static/locales/de/editProfile.json
  public/static/locales/en/common.json
  public/static/locales/en/editProfile.json
  public/static/locales/es/editProfile.json
  public/static/locales/fr/editProfile.json
  public/static/locales/it/editProfile.json
  public/static/locales/pt-BR/editProfile.json
  src/features/common/InputTypes/AutoCompleteCountry.tsx
  src/features/common/Layout/Footer/index.tsx
  src/features/common/Layout/index.tsx
  src/features/common/types/country.d.ts
  src/features/projects/components/PopupProject.tsx
  src/features/projects/components/ProjectSnippet.tsx
  src/features/projects/components/ProjectsMap.tsx
  src/features/projects/components/maps/Home.tsx
  src/features/projects/components/maps/Markers.tsx
  src/features/projects/components/maps/Project.tsx
  src/features/projects/components/projects/SearchBar.tsx
  src/features/projects/styles/ProjectSnippet.module.scss
  src/features/projects/styles/ProjectsMap.module.scss
  src/features/user/CompleteSignup/index.tsx
  src/features/user/PlanetCash/components/CreateAccountForm.tsx
  src/features/user/Settings/EditProfile/EditProfileForm.tsx
  src/features/user/Widget/DonationLink/DonationLinkForm.tsx
  src/tenants/common/Home/index.tsx
  src/tenants/common/LeaderBoard/index.tsx
  src/tenants/planet/LeaderBoard/index.tsx
  src/tenants/salesforce/Home/index.tsx
  src/tenants/stern/Home/index.tsx
  tenant.config.ts
Labels: PR: reviewed-approved
