Repository Plant-for-the-Planet-org/planet-webapp, pull requests merged in 2023-07, with the labels that each got.

#1803 Release: updates Next JS to 13 - July I
  .github/workflows/chromatic.yml
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/profile/treemapper.tsx
  src/createEmotionCache.ts
  src/features/common/InputTypes/AutoCompleteCountry.tsx
  src/features/common/InputTypes/AutoCompleteCountryNew.tsx
  src/features/common/InputTypes/BootstrapInput.tsx
  src/features/common/InputTypes/GreenRadio.tsx
  src/features/common/InputTypes/MaterialTextField.tsx
  src/features/common/Layout/PayoutsContext.tsx
  src/features/common/RedeemCode/EnterRedeemCode.tsx
  src/features/common/types/payouts.d.ts
  src/features/projects/components/ProjectsMap.tsx
  src/features/projects/components/projectDetails/ProjectContactDetails.tsx
  src/features/projects/screens/Projects.tsx
  src/features/user/Account/EditModal.tsx
  src/features/user/CompleteSignup/index.tsx
  src/features/user/ManagePayouts/components/BankAccountDetails.tsx
  src/features/user/ManagePayouts/components/BankDetailsForm.tsx
  src/features/user/ManagePayouts/components/NoBankAccount.tsx
  src/features/user/ManagePayouts/components/ReactHookFormSelect.tsx
  src/features/user/ManagePayouts/index.tsx
  src/features/user/ManagePayouts/screens/AddBankAccount.tsx
  src/features/user/ManagePayouts/screens/EditBankAccount.tsx
  src/features/user/ManagePayouts/screens/PayoutScheduleForm.tsx
  src/features/user/ManageProjects/components/BasicDetails.tsx
  src/features/user/ManageProjects/components/DetailedAnalysis.tsx
  src/features/user/ManageProjects/components/ProjectCertificates.tsx
  src/features/user/ManageProjects/components/ProjectMedia.tsx
  src/features/user/ManageProjects/components/ProjectSites.tsx
  src/features/user/ManageProjects/components/ProjectSpending.tsx
  src/features/user/ManageProjects/components/SubmitForReview.tsx
  src/features/user/PlanetCash/components/CreateAccountForm.tsx
  src/features/user/Profile/components/AddTargetModal.tsx
  src/features/user/RegisterTrees/RegisterTrees.tsx
  src/features/user/Settings/EditProfile/EditProfileForm.tsx
  src/features/user/Settings/ImpersonateUser/ImpersonateUserForm.tsx
  src/features/user/TreeMapper/Import/components/PlantingLocation.tsx
  src/features/user/TreeMapper/Import/components/SampleTreeCard.tsx
  src/features/user/TreeMapper/Import/components/SampleTrees.tsx
  src/features/user/TreeMapper/Import/components/SpeciesAutoComplete.tsx
  src/features/user/TreeMapper/MySpecies.tsx
  src/features/user/Widget/DonationLink/DonationLinkForm.tsx
  src/tenants/planet/LeaderBoard/components/LeaderBoard.module.scss
  src/tenants/planet/LeaderBoard/components/Score.tsx
  src/theme/themeStyles.ts
  src/utils/getFormattedNumber.ts
Labels: PR: reviewed-approved

#1817 Rename the table name w.r.t database migration
  pages/api/data-explorer/export.ts
  pages/api/data-explorer/species-planted.ts
  pages/api/data-explorer/total-species-planted.ts
  pages/api/data-explorer/total-trees-planted.ts
  pages/api/data-explorer/trees-planted.ts
Labels: PR: reviewed-approved, Next in line

#1819 Release: Rename table name
  pages/api/data-explorer/export.ts
  pages/api/data-explorer/species-planted.ts
  pages/api/data-explorer/total-species-planted.ts
  pages/api/data-explorer/total-trees-planted.ts
  pages/api/data-explorer/trees-planted.ts
Labels: PR: reviewed-approved

#1800 resolve codefactor errors
  .eslintrc.js
  src/features/common/types/project.d.ts
  src/features/user/ManageProjects/index.tsx
  src/utils/LayerManagerUtils.js
  src/utils/apiRequests/addServerErrors.ts
  src/utils/apiRequests/api.ts
  src/utils/apiRequests/setHeader.ts
  src/utils/browsercheck.ts
  src/utils/cleanObject.ts
  src/utils/countryCurrency/countryUtils.js
  src/utils/countryCurrency/getCurrencySymbolByCode.ts
  src/utils/countryCurrency/getFormattedDate.ts
  src/utils/countryCurrency/getStoredCurrency.ts
  src/utils/getFormattedNumber.ts
  src/utils/getImageURL.ts
  src/utils/getMetaTags/GetPublicUserProfileMeta.tsx
  src/utils/getRandomImage.ts
  src/utils/getTruncatedString.ts
  src/utils/language/getLanguageName.ts
  src/utils/maps/getMapStyle.ts
  src/utils/maps/plantLocations.ts
  src/utils/maps/zoomToProjectSite.ts
  src/utils/selectUserType.ts
  src/utils/storeConfig.ts
  src/utils/useDebouncedEffect.ts
  tenant.config.ts
  tsconfig.json
Labels: PR: reviewed-approved

#1811 ProjectPropsContext Refactor
  pages/[p].tsx
  pages/_app.tsx
  pages/index.tsx
  src/features/common/Layout/ProjectPropsContext.tsx
  src/features/common/types/ProjectPropsContextInterface.ts
  src/features/common/types/common.d.ts
  src/features/common/types/plantLocation.d.ts
  src/features/common/types/project.d.ts
  src/features/projects/components/PlantLocation/PlantLocationDetails.tsx
  src/features/projects/components/ProjectSnippet.tsx
  src/features/projects/components/ProjectsMap.tsx
  src/features/projects/components/maps/Explore.tsx
  src/features/projects/components/maps/ExploreLayers.tsx
  src/features/projects/components/maps/MapHolder.tsx
  src/features/projects/components/maps/PlantLocations.tsx
  src/features/projects/components/maps/Project.tsx
  src/features/projects/components/maps/ProjectPolygon.tsx
  src/features/projects/components/maps/ProjectTabs.tsx
  src/features/projects/components/maps/Sites.tsx
  src/features/projects/components/maps/SitesDropdown.tsx
  src/features/projects/components/maps/TimeTravel.tsx
  src/features/projects/components/projects/Filters.tsx
  src/features/projects/screens/SingleProjectDetails.tsx
  src/features/user/Account/History.tsx
  src/features/user/TreeMapper/Import/components/Map.tsx
  src/features/user/TreeMapper/components/Map.tsx
  src/utils/maps/plantLocations.ts
  src/utils/maps/zoomToProjectSite.ts
Labels: PR: reviewed-approved

#1830 Fixes missing unit cost while editing project
  src/features/user/ManageProjects/components/BasicDetails.tsx
Labels: PR: reviewed-approved

#1828 Release July II
  pages/[p].tsx
  pages/_app.tsx
  pages/index.tsx
  src/features/common/Layout/ProjectPropsContext.tsx
  src/features/common/types/ProjectPropsContextInterface.ts
  src/features/common/types/common.d.ts
  src/features/common/types/plantLocation.d.ts
  src/features/common/types/project.d.ts
  src/features/projects/components/PlantLocation/PlantLocationDetails.tsx
  src/features/projects/components/ProjectSnippet.tsx
  src/features/projects/components/ProjectsMap.tsx
  src/features/projects/components/maps/Explore.tsx
  src/features/projects/components/maps/ExploreLayers.tsx
  src/features/projects/components/maps/MapHolder.tsx
  src/features/projects/components/maps/PlantLocations.tsx
  src/features/projects/components/maps/Project.tsx
  src/features/projects/components/maps/ProjectPolygon.tsx
  src/features/projects/components/maps/ProjectTabs.tsx
  src/features/projects/components/maps/Sites.tsx
  src/features/projects/components/maps/SitesDropdown.tsx
  src/features/projects/components/maps/TimeTravel.tsx
  src/features/projects/components/projects/Filters.tsx
  src/features/projects/screens/SingleProjectDetails.tsx
  src/features/user/Account/History.tsx
  src/features/user/ManageProjects/components/BasicDetails.tsx
  src/features/user/TreeMapper/Import/components/Map.tsx
  src/features/user/TreeMapper/components/Map.tsx
  src/utils/maps/plantLocations.ts
  src/utils/maps/zoomToProjectSite.ts
Labels: PR: unreviewed
