Repository Plant-for-the-Planet-org/planet-webapp, pull requests merged in 2023-04, with the labels that each got.

#1727 Moves translations between namespaces
  public/static/locales/de/common.json
  public/static/locales/de/treemapperAnalytics.json
Labels: PR: reviewed-approved

#1635 fix route
  src/features/projects/screens/SingleProjectDetails.tsx
  src/features/user/TreeMapper/Import/components/PlantingLocation.tsx
Labels: PR: reviewed-approved

#1701 fix default country-currency
  src/features/projects/components/maps/Credits.tsx
Labels: PR: reviewed-approved

#1732 Merge main to develop
  src/utils/countryCurrency/countriesData.json
Labels: PR: reviewed-approved

#1736 Apr 23 release cleanup
  package-lock.json
  src/features/user/TreeMapper/Import/Import.module.scss
  src/features/user/TreeMapper/Import/components/PlantingLocation.tsx
Labels: Priority, PR: unreviewed, PR: reviewed-approved, Next in line

#1731 Release April II
  package-lock.json
  package.json
  src/features/projects/components/maps/Credits.tsx
  src/features/projects/components/projectDetails/ProjectContactDetails.tsx
  src/features/projects/components/projectDetails/ProjectInfo.tsx
  src/features/projects/screens/SingleProjectDetails.tsx
  src/features/projects/styles/ProjectDetails.module.scss
  src/features/user/TreeMapper/Import/Import.module.scss
  src/features/user/TreeMapper/Import/components/PlantingLocation.tsx
Labels: PR: reviewed-approved

#1721 Feature/impersonation with support pin
  package-lock.json
  package.json
  pages/claim/[type]/[code].tsx
  pages/profile/history.tsx
  pages/profile/projects/[id].tsx
  pages/profile/recurrency.tsx
  pages/profile/redeem/[code].tsx
  public/static/locales/en/me.json
  src/features/common/LandingVideo/PlayButton.tsx
  src/features/common/Layout/CookiePolicy/index.tsx
  src/features/common/Layout/UserLayout/UserLayout.module.scss
  src/features/common/Layout/UserLayout/UserLayout.tsx
  src/features/common/Layout/UserPropsContext.tsx
  src/features/common/types/user.d.ts
  src/features/user/Account/CancelModal.tsx
  src/features/user/Account/EditModal.tsx
  src/features/user/Account/PauseModal.tsx
  src/features/user/Account/ReactivateModal.tsx
  src/features/user/BulkCodes/forms/IssueCodesForm.tsx
  src/features/user/ManagePayouts/index.tsx
  src/features/user/ManagePayouts/screens/AddBankAccount.tsx
  src/features/user/ManagePayouts/screens/EditBankAccount.tsx
  src/features/user/ManagePayouts/screens/PayoutScheduleForm.tsx
  src/features/user/ManageProjects/ProjectsContainer.tsx
  src/features/user/ManageProjects/components/BasicDetails.tsx
  src/features/user/ManageProjects/components/DetailedAnalysis.tsx
  src/features/user/ManageProjects/components/ProjectCertificates.tsx
  src/features/user/ManageProjects/components/ProjectMedia.tsx
  src/features/user/ManageProjects/components/ProjectSites.tsx
  src/features/user/ManageProjects/components/ProjectSpending.tsx
  src/features/user/ManageProjects/index.tsx
  src/features/user/PlanetCash/components/CreateAccountForm.tsx
  src/features/user/PlanetCash/index.tsx
  src/features/user/PlanetCash/screens/Transactions.tsx
  src/features/user/Profile/components/AddTargetModal.tsx
  src/features/user/Profile/components/MyTrees/MyTrees.tsx
  src/features/user/Profile/components/RedeemModal.tsx
  src/features/user/Profile/index.tsx
  src/features/user/RegisterTrees/RegisterTrees.tsx
  src/features/user/RegisterTrees/RegisterTrees/UploadImages.tsx
  src/features/user/Settings/ApiKey.tsx
  src/features/user/Settings/DeleteProfile.tsx
  src/features/user/Settings/EditProfile.tsx
  src/features/user/Settings/ImpersonateUser/ImpersonateUserForm.tsx
  src/features/user/Settings/ImpersonateUser/ImpersonationActivated.tsx
  src/features/user/Settings/ImpersonateUser/SupportPin.tsx
  src/features/user/TreeMapper/Analytics/index.tsx
  src/features/user/TreeMapper/Import/components/PlantingLocation.tsx
  src/features/user/TreeMapper/Import/components/SampleTrees.tsx
  src/features/user/TreeMapper/Import/index.tsx
  src/features/user/TreeMapper/MySpecies.tsx
  src/features/user/TreeMapper/index.tsx
  src/features/user/Widget/EmbedModal.tsx
  src/utils/apiRequests/api.ts
  src/utils/apiRequests/setHeader.ts
Labels: Priority, PR: reviewed-approved, Next in line

#1744 Release Impersonation with Pin
  package-lock.json
  package.json
  pages/claim/[type]/[code].tsx
  pages/profile/history.tsx
  pages/profile/projects/[id].tsx
  pages/profile/recurrency.tsx
  pages/profile/redeem/[code].tsx
  public/static/locales/en/me.json
  src/features/common/LandingVideo/PlayButton.tsx
  src/features/common/Layout/CookiePolicy/index.tsx
  src/features/common/Layout/UserLayout/UserLayout.module.scss
  src/features/common/Layout/UserLayout/UserLayout.tsx
  src/features/common/Layout/UserPropsContext.tsx
  src/features/common/types/user.d.ts
  src/features/user/Account/CancelModal.tsx
  src/features/user/Account/EditModal.tsx
  src/features/user/Account/PauseModal.tsx
  src/features/user/Account/ReactivateModal.tsx
  src/features/user/BulkCodes/forms/IssueCodesForm.tsx
  src/features/user/ManagePayouts/index.tsx
  src/features/user/ManagePayouts/screens/AddBankAccount.tsx
  src/features/user/ManagePayouts/screens/EditBankAccount.tsx
  src/features/user/ManagePayouts/screens/PayoutScheduleForm.tsx
  src/features/user/ManageProjects/ProjectsContainer.tsx
  src/features/user/ManageProjects/components/BasicDetails.tsx
  src/features/user/ManageProjects/components/DetailedAnalysis.tsx
  src/features/user/ManageProjects/components/ProjectCertificates.tsx
  src/features/user/ManageProjects/components/ProjectMedia.tsx
  src/features/user/ManageProjects/components/ProjectSites.tsx
  src/features/user/ManageProjects/components/ProjectSpending.tsx
  src/features/user/ManageProjects/index.tsx
  src/features/user/PlanetCash/components/CreateAccountForm.tsx
  src/features/user/PlanetCash/index.tsx
  src/features/user/PlanetCash/screens/Transactions.tsx
  src/features/user/Profile/components/AddTargetModal.tsx
  src/features/user/Profile/components/MyTrees/MyTrees.tsx
  src/features/user/Profile/components/RedeemModal.tsx
  src/features/user/Profile/index.tsx
  src/features/user/RegisterTrees/RegisterTrees.tsx
  src/features/user/RegisterTrees/RegisterTrees/UploadImages.tsx
  src/features/user/Settings/ApiKey.tsx
  src/features/user/Settings/DeleteProfile.tsx
  src/features/user/Settings/EditProfile.tsx
  src/features/user/Settings/ImpersonateUser/ImpersonateUserForm.tsx
  src/features/user/Settings/ImpersonateUser/ImpersonationActivated.tsx
  src/features/user/Settings/ImpersonateUser/SupportPin.tsx
  src/features/user/TreeMapper/Analytics/index.tsx
  src/features/user/TreeMapper/Import/components/PlantingLocation.tsx
  src/features/user/TreeMapper/Import/components/SampleTrees.tsx
  src/features/user/TreeMapper/Import/index.tsx
  src/features/user/TreeMapper/MySpecies.tsx
  src/features/user/TreeMapper/index.tsx
  src/features/user/Widget/EmbedModal.tsx
  src/utils/apiRequests/api.ts
  src/utils/apiRequests/setHeader.ts
Labels: PR: reviewed-approved

#1587 Add Verified and Top Project Badge
  package-lock.json
  package.json
  public/static/locales/de/common.json
  public/static/locales/en/common.json
  src/features/projects/components/PopupProject.tsx
  src/features/projects/components/ProjectSnippet.tsx
  src/features/projects/components/projectDetails/TopProjectReports.tsx
  src/features/projects/screens/Projects.tsx
  src/features/projects/screens/SingleProjectDetails.tsx
  src/features/projects/styles/ProjectDetails.module.scss
  src/features/projects/styles/ProjectSnippet.module.scss
  src/features/user/Profile/ProjectsContainer.tsx
Labels: Priority, PR: unreviewed, PR: reviewed-approved, Next in line

#1607 Feature/show top projects list
  .env.local.example
  src/features/projects/components/projects/Header.tsx
  src/features/projects/screens/Projects.tsx
Labels: Priority, PR: unreviewed, PR: reviewed-approved, PR: partially-approved, Next in line

#1714 fix: resolves hidden banner text on small screens
  src/tenants/salesforce/Home/styles/Landing.module.scss
Labels: PR: reviewed-approved

#1751 Release Verified & Top-Projects
  .env.local.example
  package-lock.json
  package.json
  public/static/locales/cs/common.json
  public/static/locales/cs/donate.json
  public/static/locales/cs/me.json
  public/static/locales/de/common.json
  public/static/locales/de/me.json
  public/static/locales/en/common.json
  public/static/locales/pt-BR/common.json
  src/features/projects/components/PopupProject.tsx
  src/features/projects/components/ProjectSnippet.tsx
  src/features/projects/components/projectDetails/TopProjectReports.tsx
  src/features/projects/components/projects/Header.tsx
  src/features/projects/screens/Projects.tsx
  src/features/projects/screens/SingleProjectDetails.tsx
  src/features/projects/styles/ProjectDetails.module.scss
  src/features/projects/styles/ProjectSnippet.module.scss
  src/features/user/Profile/ProjectsContainer.tsx
  src/tenants/salesforce/Home/styles/Landing.module.scss
Labels: PR: reviewed-approved

#1749 Disable non working toggles for current forests/restoration potential
  src/features/common/InputTypes/ToggleSwitch.tsx
  src/features/projects/components/maps/Explore.tsx
  src/features/projects/components/projects/Filters.tsx
  src/features/user/CompleteSignup/index.tsx
  src/features/user/ManageProjects/components/BasicDetails.tsx
Labels: PR: reviewed-approved

#1753 Updates webpack from 5.74.0 to 5.76.0
  package-lock.json
  package.json
Labels: PR: reviewed-approved

#1756 Adds comments reg. vegetation tab display logic on project details page
  src/features/projects/components/maps/Project.tsx
  src/features/projects/components/maps/ProjectTabs.tsx
Labels: PR: reviewed-approved
