Repository Plant-for-the-Planet-org/planet-webapp, pull requests merged in 2023-03, with the labels that each got.

#1695 Fixes web share issue
  src/features/user/Profile/components/UserProfileOptions.tsx
Labels: PR: reviewed-approved

#1696 Release Hotfix: Fix Web Share Issue
  src/features/user/Profile/components/UserProfileOptions.tsx
Labels: PR: partially-approved

#1697 Resolves translation issues on leaderboard
  public/static/locales/de/common.json
  public/static/locales/en/common.json
  public/static/locales/es/common.json
  public/static/locales/fr/common.json
  public/static/locales/it/common.json
  public/static/locales/pt-BR/common.json
  src/features/projects/components/ProjectSnippet.tsx
  src/features/user/BulkCodes/components/BulkGiftTotal.tsx
  src/tenants/salesforce/Home/components/LeaderBoardSection.tsx
Labels: PR: reviewed-approved

#1698 Release: Resolve translation issues on Leaderboards
  public/static/locales/de/common.json
  public/static/locales/en/common.json
  public/static/locales/es/common.json
  public/static/locales/fr/common.json
  public/static/locales/it/common.json
  public/static/locales/pt-BR/common.json
  src/features/projects/components/ProjectSnippet.tsx
  src/features/user/BulkCodes/components/BulkGiftTotal.tsx
  src/tenants/salesforce/Home/components/LeaderBoardSection.tsx
Labels: PR: reviewed-approved

#1699 fix scrollbar
  src/features/common/Layout/UserLayout/UserLayout.module.scss
Labels: PR: reviewed-approved

#1708 Hide scrollbar
  package-lock.json
  src/features/common/Layout/UserLayout/UserLayout.module.scss
Labels: PR: reviewed-approved

#1713 fix: resolves hidden banner text on small screens
  src/tenants/salesforce/Home/styles/Landing.module.scss
Labels: PR: unreviewed

#1719 Simpler use of the connection string
  src/utils/connectDB.ts
Labels: PR: reviewed-approved
