Repository Plant-for-the-Planet-org/planet-webapp, pull requests merged in 2024-01, with the labels that each got.

#1950 Updates text on salesforce home page
  src/tenants/salesforce/Home/components/ContentSection.tsx
  src/tenants/salesforce/Home/components/Landing.tsx
  src/tenants/salesforce/Home/styles/Landing.module.scss
  src/tenants/salesforce/TreeCounter/TreeCounter.module.scss
  src/tenants/salesforce/TreeCounter/TreeCounter.tsx
Labels: PR: reviewed-approved

#1952 Updates TreeCounter to match changes in SF branch
  src/tenants/salesforce/Home/components/Landing.tsx
  src/tenants/salesforce/TreeCounter/TreeCounter.module.scss
  src/tenants/salesforce/TreeCounter/TreeCounter.tsx
Labels: PR: unreviewed

#1951 Release January 2024 I
  package-lock.json
  package.json
  src/tenants/salesforce/Home/components/ContentSection.tsx
  src/tenants/salesforce/Home/components/Landing.tsx
  src/tenants/salesforce/Home/styles/Landing.module.scss
  src/tenants/salesforce/TreeCounter/TreeCounter.module.scss
  src/tenants/salesforce/TreeCounter/TreeCounter.tsx
  src/utils/countryZipCode/index.js
Labels: PR: reviewed-changes-requested

#1955 fixed wrong not existing link to privacy
  src/features/common/Layout/CookiePolicy/index.tsx
Labels: PR: reviewed-approved

#1935 [Snyk] Security upgrade npm from 9.9.1 to 10.2.2
  package.json
Labels: PR: reviewed-approved

#1956 Release Upgrade npm to 10.2.2 and link fix
  package.json
  src/features/common/Layout/CookiePolicy/index.tsx
Labels: PR: reviewed-approved

#1954 fixed layout of manage projects index page
  src/features/user/ManageProjects/ProjectsContainer.tsx
Labels: PR: unreviewed

#1953 Update storybook to v7.6
  .eslintrc.js
  .github/workflows/chromatic.yml
  .storybook/i18n.js
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  package.json
  src/features/common/Layout/BulkCodeContext.tsx
  src/features/common/types/project.d.ts
  src/features/user/BulkCodes/BulkCodesTypes.d.ts
  src/features/user/BulkCodes/components/BulkGiftTotal.tsx
  src/features/user/BulkCodes/components/ProjectSelectAutocomplete.tsx
  src/features/user/BulkCodes/components/UnitCostDisplay.tsx
  src/features/user/BulkCodes/components/UploadWidget.tsx
  src/features/user/BulkCodes/stories/BulkGiftTotal.stories.tsx
  src/features/user/BulkCodes/stories/Button.stories.tsx
  src/features/user/BulkCodes/stories/ProjectSelectAutocomplete.stories.tsx
  src/features/user/BulkCodes/stories/RecipientsTable.stories.tsx
  src/features/user/BulkCodes/stories/RecipientsUploadForm.stories.tsx
  src/features/user/BulkCodes/stories/SelectorOption.stories.tsx
  src/features/user/BulkCodes/stories/UnitCostDisplay.stories.tsx
  src/features/user/BulkCodes/stories/UploadWidget.stories.tsx
Labels: PR: reviewed-approved

#1957 Release January II
  .eslintrc.js
  .github/workflows/chromatic.yml
  .storybook/i18n.js
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  package.json
  src/features/common/Layout/BulkCodeContext.tsx
  src/features/common/types/project.d.ts
  src/features/user/BulkCodes/BulkCodesTypes.d.ts
  src/features/user/BulkCodes/components/BulkGiftTotal.tsx
  src/features/user/BulkCodes/components/ProjectSelectAutocomplete.tsx
  src/features/user/BulkCodes/components/UnitCostDisplay.tsx
  src/features/user/BulkCodes/components/UploadWidget.tsx
  src/features/user/BulkCodes/stories/BulkGiftTotal.stories.tsx
  src/features/user/BulkCodes/stories/Button.stories.tsx
  src/features/user/BulkCodes/stories/ProjectSelectAutocomplete.stories.tsx
  src/features/user/BulkCodes/stories/RecipientsTable.stories.tsx
  src/features/user/BulkCodes/stories/RecipientsUploadForm.stories.tsx
  src/features/user/BulkCodes/stories/SelectorOption.stories.tsx
  src/features/user/BulkCodes/stories/UnitCostDisplay.stories.tsx
  src/features/user/BulkCodes/stories/UploadWidget.stories.tsx
  src/features/user/ManageProjects/ProjectsContainer.tsx
Labels: PR: reviewed-approved

#1856 feat:types for map
  package-lock.json
  package.json
  src/features/common/CopyToClipboard/index.tsx
  src/features/common/types/map.d.ts
  src/features/common/types/plantLocation.d.ts
  src/features/projects/components/ProjectsMap.tsx
  src/features/projects/components/maps/Markers.tsx
  src/features/projects/components/maps/PlantLocations.tsx
  src/features/projects/components/projectDetails/ImageSlider.tsx
  src/features/user/Profile/components/MyTrees/MyTrees.tsx
  src/features/user/RegisterTrees/RegisterTrees/DrawMap.tsx
  src/features/user/RegisterTrees/RegisterTrees/SingleContribution.tsx
  src/features/user/RegisterTrees/RegisterTrees/StaticMap.tsx
  src/features/user/RegisterTrees/RegisterTreesWidget.tsx
  src/features/user/TreeMapper/Import/components/Map.tsx
  src/features/user/TreeMapper/Import/components/MapComponent.tsx
  src/features/user/TreeMapper/Import/index.tsx
  src/features/user/TreeMapper/components/Map.tsx
  src/features/user/TreeMapper/components/PlantLocation.tsx
  src/features/user/TreeMapper/components/PlantLocationPage.tsx
  src/features/user/TreeMapper/components/TreeMapperList.tsx
  src/features/user/TreeMapper/index.tsx
Labels: PR: reviewed-changes-requested

#1962 Release: Types for maps
  package-lock.json
  package.json
  src/features/common/CopyToClipboard/index.tsx
  src/features/common/types/map.d.ts
  src/features/common/types/plantLocation.d.ts
  src/features/projects/components/ProjectsMap.tsx
  src/features/projects/components/maps/Markers.tsx
  src/features/projects/components/maps/PlantLocations.tsx
  src/features/projects/components/projectDetails/ImageSlider.tsx
  src/features/user/Profile/components/MyTrees/MyTrees.tsx
  src/features/user/RegisterTrees/RegisterTrees/DrawMap.tsx
  src/features/user/RegisterTrees/RegisterTrees/SingleContribution.tsx
  src/features/user/RegisterTrees/RegisterTrees/StaticMap.tsx
  src/features/user/RegisterTrees/RegisterTreesWidget.tsx
  src/features/user/TreeMapper/Import/components/Map.tsx
  src/features/user/TreeMapper/Import/components/MapComponent.tsx
  src/features/user/TreeMapper/Import/index.tsx
  src/features/user/TreeMapper/components/Map.tsx
  src/features/user/TreeMapper/components/PlantLocation.tsx
  src/features/user/TreeMapper/components/PlantLocationPage.tsx
  src/features/user/TreeMapper/components/TreeMapperList.tsx
  src/features/user/TreeMapper/index.tsx
Labels: PR: reviewed-approved
