Repository Plant-for-the-Planet-org/planet-webapp, pull requests merged in 2024-05, with the labels that each got.

#2055 Resolve multiple api calls in data explorer
  src/features/user/TreeMapper/Analytics/components/Export/index.tsx
  src/features/user/TreeMapper/Analytics/components/Map/index.tsx
  src/features/user/TreeMapper/Analytics/components/ProjectFilter/index.tsx
  src/utils/useDebouncedEffect.ts
Labels: PR: reviewed-approved

#2024 [Snyk] Security upgrade express from 4.18.2 to 4.19.2
  package.json
Labels: dependencies, PR: unreviewed

#2061 Release small fixes May 2024
  app.json
  next.config.js
  package.json
  pages/sites/[slug]/[locale]/all.tsx
  src/features/common/types/leaderboard.d.ts
  src/features/user/TreeMapper/Analytics/components/Export/index.tsx
  src/features/user/TreeMapper/Analytics/components/Map/index.tsx
  src/features/user/TreeMapper/Analytics/components/ProjectFilter/index.tsx
  src/tenants/planet/LeaderBoard/components/Stats.tsx
  src/tenants/planet/LeaderBoard/index.tsx
  src/utils/useDebouncedEffect.ts
Labels: PR: reviewed-approved

#2064 trpc APIs for MyForest v2.0
  prisma/schema.prisma
  src/features/common/types/myForestv2.d.ts
  src/server/procedures/myForestV2/contributions.ts
  src/server/procedures/myForestV2/projectList.ts
  src/server/router/_app.ts
  src/server/router/myForest.ts
  src/utils/getPointCoordinates.ts
Labels: MyForest 2.0

#2059 Profile card: My forest v2
  .storybook/preview.js
  package-lock.json
  package.json
  pages/sites/[slug]/[locale]/claim/[type]/[code].tsx
  pages/sites/[slug]/[locale]/mfv2-public/[profile].tsx
  pages/sites/[slug]/[locale]/profile/mfv2.tsx
  public/assets/images/icons/ProfilePageV2Icons.tsx
  public/assets/images/profileBackground.jpg
  public/static/locales/en/profile.json
  src/features/common/ContentLoaders/ProfileV2/index.tsx
  src/features/common/ContentLoaders/ProfileV2/profileV2ContentLoaders.module.scss
  src/features/common/CopyToClipboard/index.tsx
  src/features/common/types/profile.d.ts
  src/features/user/MFV2/ProfileCard/ProfileActions/ProfileActions.module.scss
  src/features/user/MFV2/ProfileCard/ProfileActions/SocialMediaShareButton.tsx
  src/features/user/MFV2/ProfileCard/ProfileActions/index.tsx
  src/features/user/MFV2/ProfileCard/ProfileCard.module.scss
  src/features/user/MFV2/ProfileCard/ProfileCardButton/ProfileCardButton.module.scss
  src/features/user/MFV2/ProfileCard/ProfileCardButton/index.tsx
  src/features/user/MFV2/ProfileCard/ShareModal/ShareModal.module.scss
  src/features/user/MFV2/ProfileCard/ShareModal/index.tsx
  src/features/user/MFV2/ProfileCard/index.tsx
  src/features/user/MFV2/ProfileLayout/ProfileLayout.module.scss
  src/features/user/MFV2/ProfileLayout/index.tsx
  src/features/user/MFV2/PublicProfileLayout/PublicProfileLayout.module.scss
  src/features/user/MFV2/PublicProfileLayout/index.tsx
  src/features/user/MFV2/PublicProfileOuterContainer/PublicProfileOuterContainer.module.scss
  src/features/user/MFV2/stories/ProfileActions.stories.tsx
  src/features/user/MFV2/stories/ProfileCard.stories.tsx
  src/features/user/MFV2/stories/ShareModal.stories.tsx
  src/features/user/Profile/components/ProfileBox/microComponents/RedeemModal.tsx
Labels: PR: reviewed-approved, MyForest 2.0

#2073 Adds Leaderboard Api for myForest v2
  src/features/common/types/myForestv2.d.ts
  src/server/procedures/myForestV2/contributions.ts
  src/server/procedures/myForestV2/leaderboard.ts
  src/server/router/myForest.ts
  src/server/utils/fetchGroupTreecounterData.ts
  src/server/utils/fetchProfile.ts
Labels: MyForest 2.0

#2058 Feature/my forest v2 map layout (MAP BASE)
  package-lock.json
  package.json
  prisma/schema.prisma
  public/data/styles/MyForestMapStyles.json
  src/features/common/types/myForestv2.d.ts
  src/features/user/MFV2/ContributionsMap/index.tsx
  src/features/user/MFV2/ProfileLayout/ProfileLayout.module.scss
  src/features/user/MFV2/ProfileLayout/index.tsx
  src/server/procedures/myForestV2/contributions.ts
  src/server/procedures/myForestV2/leaderboard.ts
  src/server/procedures/myForestV2/projectList.ts
  src/server/router/_app.ts
  src/server/router/myForest.ts
  src/server/utils/fetchGroupTreecounterData.ts
  src/server/utils/fetchProfile.ts
  src/utils/getPointCoordinates.ts
  src/utils/maps/getMapStyle.ts
Labels: MyForest 2.0

#2077 Fixes queries for contributions API to avoid null gift plantdate
  src/server/procedures/myForestV2/contributions.ts
Labels: MyForest 2.0

#2081 Release small changes Bulk Codes & Payment History
  src/features/user/Account/components/AccountRecord.tsx
  src/features/user/Account/components/Certificates.tsx
  src/features/user/BulkCodes/index.tsx
Labels: PR: unreviewed

#2080 Contributions API - Uses project country as a backup for missing country value in contributions/gifts
  src/server/procedures/myForestV2/contributions.ts
Labels: MyForest 2.0

#2071 Refactors map for better performance while showing a single project
  src/features/common/types/plantLocation.d.ts
  src/features/projects/components/ProjectsMap.tsx
  src/features/projects/components/maps/PlantLocations.tsx
Labels: PR: reviewed-approved

#2072 MY FOREST - Redesign edit profile
  public/assets/images/icons/userProfileIcons/Camera.tsx
  public/static/locales/en/editProfile.json
  src/features/common/InputTypes/AutoCompleteCountry.tsx
  src/features/common/InputTypes/NewToggleSwitch.tsx
  src/features/common/Layout/Forms/InlineFormDisplayGroup.tsx
  src/features/user/Settings/EditProfile/CustomTooltip.tsx
  src/features/user/Settings/EditProfile/EditProfile.module.scss
  src/features/user/Settings/EditProfile/EditProfileForm.tsx
  src/features/user/Settings/EditProfile/index.tsx
  src/utils/selectUserType.ts
Labels: PR: reviewed-changes-requested, MyForest 2.0
