Repository Plant-for-the-Planet-org/planet-webapp, pull requests merged in 2024-04, with the labels that each got.

#2027 Updates caching key naming logic to use api endpoint
  src/utils/multiTenancy/helpers.ts
Labels: PR: reviewed-approved

#1892 Map in Data Explorer
  package-lock.json
  package.json
  pages/api/data-explorer/export.ts
  pages/api/data-explorer/map/distinct-species/[projectId].ts
  pages/api/data-explorer/map/plant-location/[plantLocationId].ts
  pages/api/data-explorer/map/plant-location/index.ts
  pages/api/data-explorer/map/sites/[projectId].ts
  pages/api/data-explorer/species-planted.ts
  pages/api/data-explorer/total-species-planted.ts
  pages/api/data-explorer/total-trees-planted.ts
  pages/api/data-explorer/trees-planted.ts
  pages/profile/treemapper/data-explorer.tsx
  public/static/locales/en/treemapperAnalytics.json
  src/features/common/types/dataExplorer.d.ts
  src/features/user/TreeMapper/Analytics/components/Container/index.module.scss
  src/features/user/TreeMapper/Analytics/components/Container/index.tsx
  src/features/user/TreeMapper/Analytics/components/DataExplorerGridContainer/index.tsx
  src/features/user/TreeMapper/Analytics/components/Export/index.module.scss
  src/features/user/TreeMapper/Analytics/components/Export/index.tsx
  src/features/user/TreeMapper/Analytics/components/Map/components/LeftControls/index.module.scss
  src/features/user/TreeMapper/Analytics/components/Map/components/LeftControls/index.tsx
  src/features/user/TreeMapper/Analytics/components/Map/components/PlantLocationDetails/index.module.scss
  src/features/user/TreeMapper/Analytics/components/Map/components/PlantLocationDetails/index.tsx
  src/features/user/TreeMapper/Analytics/components/Map/components/PlantLocationDetailsZeroState.tsx
  src/features/user/TreeMapper/Analytics/components/Map/components/SiteSelectorAutocomplete/index.tsx
  src/features/user/TreeMapper/Analytics/components/Map/components/TreeMapperIcon.tsx
  src/features/user/TreeMapper/Analytics/components/Map/index.module.scss
  src/features/user/TreeMapper/Analytics/components/Map/index.tsx
  src/features/user/TreeMapper/Analytics/components/NoProjectsFound/index.tsx
  src/features/user/TreeMapper/Analytics/components/ProjectTypeSelector.tsx
  src/features/user/TreeMapper/Analytics/components/SpeciesPlanted/index.module.scss
  src/features/user/TreeMapper/Analytics/components/SpeciesPlanted/index.tsx
  src/features/user/TreeMapper/Analytics/components/TreePlanted/index.module.scss
  src/features/user/TreeMapper/Analytics/components/TreePlanted/index.tsx
  src/features/user/TreeMapper/Analytics/constants.ts
  src/features/user/TreeMapper/Analytics/index.tsx
Labels: PR: reviewed-approved

#2036 Release Message Redemption Self Gift & change in CtA
  pages/sites/[slug]/claim/[type]/[code].tsx
  pages/sites/[slug]/profile/redeem/[code].tsx
  public/assets/images/membership-bg-image.jpg
  public/static/locales/cs/donate.json
  public/static/locales/cs/me.json
  public/static/locales/cs/profile.json
  public/static/locales/de/donate.json
  public/static/locales/de/editProfile.json
  public/static/locales/de/me.json
  public/static/locales/de/profile.json
  public/static/locales/de/redeem.json
  public/static/locales/de/treemapper.json
  public/static/locales/en/bulkCodes.json
  public/static/locales/en/donate.json
  public/static/locales/en/editProfile.json
  public/static/locales/en/me.json
  public/static/locales/en/profile.json
  public/static/locales/en/redeem.json
  public/static/locales/en/treemapperAnalytics.json
  public/static/locales/es/donate.json
  public/static/locales/es/me.json
  public/static/locales/es/profile.json
  public/static/locales/fr/donate.json
  public/static/locales/fr/me.json
  public/static/locales/fr/profile.json
  public/static/locales/it/common.json
  public/static/locales/it/me.json
  public/static/locales/it/profile.json
  public/static/locales/pt-BR/donate.json
  public/static/locales/pt-BR/me.json
  public/static/locales/pt-BR/profile.json
  src/features/user/Account/AccountHistory.module.scss
  src/features/user/Account/components/MembershipCta.tsx
  src/features/user/Profile/components/ProfileBox/microComponents/RedeemModal.tsx
Labels: PR: reviewed-approved

#2039 remove links to a.plant-for-the-planet.org
  pages/_document.tsx
  public/tenants/3pleset/config.ts
  public/tenants/culchacandela/config.ts
  public/tenants/energizer/config.ts
  public/tenants/interactClub/config.ts
  public/tenants/lacoqueta/config.ts
  public/tenants/nitrosb/config.ts
  public/tenants/pampers/config.ts
  public/tenants/planet/config.ts
  public/tenants/planet/configBeta.ts
  public/tenants/salesforce/config.ts
  public/tenants/senatDerWirtschaft/config.ts
  public/tenants/sitex/config.ts
  public/tenants/stern/config.ts
  public/tenants/ttc/config.ts
  public/tenants/ulmpflanzt/config.ts
  public/tenants/weareams/config.ts
  public/tenants/xiting/config.ts
  src/features/common/LandingVideo/index.tsx
  src/features/common/Layout/Footer/index.tsx
  src/features/common/Layout/Navbar/index.tsx
  src/tenants/planet/LeaderBoard/components/Stories.tsx
  tenant.config.ts
Labels: PR: reviewed-approved

#2040 Adds group treecounter support for Myforest
  src/features/user/Profile/components/MyContributions/index.tsx
  src/server/procedures/myForest/contributions.ts
  src/server/procedures/myForest/contributionsGeoJson.ts
  src/server/procedures/myForest/stats.ts
Labels: PR: reviewed-approved

#1973 Feature/redesign about section
  .github/workflows/chromatic.yml
  public/static/locales/en/projectDetails.json
  src/temp/AboutSection/AboutProject.module.scss
  src/temp/AboutSection/AboutProject.tsx
  src/temp/AboutSection/ToggleDescriptionButton.module.scss
  src/temp/AboutSection/ToggleDescriptionButton.tsx
  src/temp/icons/DownArrow.tsx
  src/temp/icons/UpArrow.tsx
  src/temp/stories/About.stories.tsx
  src/theme/_colors.scss
  src/theme/theme.ts
  src/theme/themeProperties.ts
Labels: PR: reviewed-changes-requested, projects redesign

#1968 Redesign site dropdown
  .github/workflows/chromatic.yml
  public/static/locales/en/manageProjects.json
  src/temp/ProjectSiteDropdown/SiteDropdown.module.scss
  src/temp/ProjectSiteDropdown/index.tsx
  src/temp/icons/SiteIcon.tsx
  src/temp/stories/Sites.stories.tsx
  src/theme/_colors.scss
  src/theme/theme.ts
  src/theme/themeProperties.ts
Labels: PR: reviewed-changes-requested, projects redesign

#1970 Redesign project snippet components
  .github/workflows/chromatic.yml
  public/static/locales/en/projectDetails.json
  src/temp/ProjectBadge/Badge.module.scss
  src/temp/ProjectBadge/ProjectBadge.tsx
  src/temp/icons/FieldReviewedIcon.tsx
  src/temp/icons/OffSiteReviewedIcon.tsx
  src/temp/icons/TopProjectIcon.tsx
  src/temp/stories/ProjectBadge.stories.tsx
Labels: PR: reviewed-approved, projects redesign

#1991 Time Travel Dropdown
  .github/workflows/chromatic.yml
  src/temp/TimeTravelDropdown/Dropdown.module.scss
  src/temp/TimeTravelDropdown/index.tsx
  src/temp/icons/CalendarIcon.tsx
  src/temp/stories/TimeTravelDropdown.stories.tsx
  src/theme/_colors.scss
  src/theme/theme.ts
  src/theme/themeProperties.ts
Labels: PR: reviewed-approved, projects redesign

#1969 Design Forest Fire Popup
  .github/workflows/chromatic.yml
  public/static/locales/en/projectDetails.json
  src/temp/FirePopup/FirePopup.module.scss
  src/temp/FirePopup/index.tsx
  src/temp/icons/FireIcon.tsx
  src/temp/icons/FirePopupIcon.tsx
  src/temp/stories/FirePopup.stories.tsx
  src/theme/_colors.scss
  src/theme/theme.ts
  src/theme/themeProperties.ts
Labels: PR: reviewed-approved, projects redesign

#1985 dive into the project button
  .github/workflows/chromatic.yml
  package-lock.json
  public/static/locales/en/projectDetails.json
  src/temp/MapPreview/MapPreview.module.scss
  src/temp/MapPreview/ShowMapButton.tsx
  src/temp/MapPreview/index.tsx
  src/temp/icons/ExpandIcon.tsx
  src/temp/stories/MapPreview.stories.tsx
Labels: PR: reviewed-approved, projects redesign

#1974 Feature/design project info container
  .github/workflows/chromatic.yml
  public/static/locales/en/projectDetails.json
  src/temp/ProjectInfo/AdditionalInfo.tsx
  src/temp/ProjectInfo/ContactDetails.tsx
  src/temp/ProjectInfo/DownloadButton.tsx
  src/temp/ProjectInfo/DownloadsLabel.tsx
  src/temp/ProjectInfo/ExternalCertificationItem.tsx
  src/temp/ProjectInfo/KeyInfo.tsx
  src/temp/ProjectInfo/PlantingSeasons.tsx
  src/temp/ProjectInfo/ProgressReportItem.tsx
  src/temp/ProjectInfo/ProjectDownloads.tsx
  src/temp/ProjectInfo/ProjectInfo.module.scss
  src/temp/ProjectInfo/ProjectSpendingItem.tsx
  src/temp/ProjectInfo/SingleContactDetail.tsx
  src/temp/ProjectInfo/SingleProjectInfoItem.tsx
  src/temp/icons/DownloadIcon.tsx
  src/temp/icons/LocationIcon.tsx
  src/temp/icons/MailIcon.tsx
  src/temp/icons/ViewProfileIcon.tsx
  src/temp/icons/WebsiteLinkIcon.tsx
  src/temp/stories/AdditionalInfo.stories.tsx
  src/temp/stories/Contacts.stories.tsx
  src/temp/stories/KeyInfo.stories.tsx
  src/temp/stories/ProjectDownloads.stories.tsx
  src/theme/_colors.scss
  src/theme/theme.ts
  src/theme/themeProperties.ts
Labels: PR: reviewed-approved, PR: reviewed-changes-requested, projects redesign

#1965 explore button
  .github/workflows/chromatic.yml
  public/static/locales/en/allProjects.json
  src/temp/Explore/CustomButton.tsx
  src/temp/Explore/CustomSlider.tsx
  src/temp/Explore/CustomSwitch.tsx
  src/temp/Explore/Explore.module.scss
  src/temp/Explore/ExploreProject.tsx
  src/temp/Explore/MapLayerOptions.tsx
  src/temp/icons/ExploreIcon.tsx
  src/temp/icons/InfoIcon.tsx
  src/temp/icons/PlayIcon.tsx
  src/temp/stories/ExploreProject.stories.tsx
  src/theme/_colors.scss
  src/theme/_fonts.scss
  src/theme/theme.ts
  src/theme/themeProperties.ts
Labels: PR: reviewed-changes-requested, projects redesign
