Repository Plant-for-the-Planet-org/planet-webapp, pull requests merged in 2024-07, with the labels that each got.

#2124 fix: align popup properly by removing offset and anchor properties
  src/features/user/MFV2/ContributionsMap/Markers/PointMarkers.tsx
  src/features/user/MFV2/ContributionsMap/Popup/DonationPopup.tsx
  src/features/user/MFV2/ContributionsMap/Popup/RegisteredTreesPopup.tsx
Labels: PR: reviewed-approved, MyForest 2.0

#2122 Addresses testing feedback for My Forest V2
  public/assets/images/icons/project/ManagedRegeneration.tsx
  src/features/user/MFV2/ContributionsMap/Markers/DonationClusterMarker.tsx
  src/features/user/MFV2/ContributionsMap/Markers/index.tsx
  src/features/user/MFV2/ContributionsMap/index.tsx
  src/features/user/MFV2/ForestProgress/ForestProgressItem.tsx
  src/features/user/MFV2/ForestProgress/microComponents/ProgressData.tsx
  src/features/user/MFV2/ForestProgress/microComponents/StackedBarGraph.tsx
  src/server/procedures/myForestV2/contributions.ts
  src/utils/myForestV2Utils.ts
  src/utils/superclusterConfig.ts
Labels: PR: unreviewed, MyForest 2.0

#2121 Remove progressContainer from the grid when it isn't shown
  src/features/user/MFV2/PublicProfileLayout/PublicProfileLayout.module.scss
  src/features/user/MFV2/PublicProfileLayout/index.tsx
Labels: PR: reviewed-approved, MyForest 2.0

#2117 InfoAndCtaContainer: SDG Cards Section
  package-lock.json
  package.json
  public/assets/images/icons/ProfilePageV2Icons.tsx
  public/assets/images/publicProfileActionsImages/forestRestorationAndConservation.png
  public/assets/images/publicProfileActionsImages/restorationAdvice.png
  public/assets/images/publicProfileActionsImages/restorationTools.png
  public/assets/images/publicProfileActionsImages/youthEmpowerment.png
  public/assets/images/sdgCards/Goal-04.png
  public/assets/images/sdgCards/Goal-08.png
  public/assets/images/sdgCards/Goal-09.png
  public/assets/images/sdgCards/Goal-10.png
  public/assets/images/sdgCards/Goal-13.png
  public/assets/images/sdgCards/Goal-15.png
  public/assets/images/sdgCards/Goal-17.png
  public/static/locales/en/profile.json
  src/features/common/CarouselSlider/CarouselSlider.module.scss
  src/features/common/CarouselSlider/index.tsx
  src/features/user/MFV2/InfoAndCTA/InfoAndCta.module.scss
  src/features/user/MFV2/InfoAndCTA/PublicProfileActions/PublicProfileActionCard.tsx
  src/features/user/MFV2/InfoAndCTA/PublicProfileActions/PublicProfileActionsHeader.tsx
  src/features/user/MFV2/InfoAndCTA/PublicProfileActions/index.tsx
  src/features/user/MFV2/InfoAndCTA/SDGCardList/index.tsx
  src/features/user/MFV2/InfoAndCTA/index.tsx
  src/features/user/MFV2/ProfileCard/ProfileActions/ProfileActions.module.scss
  src/features/user/MFV2/ProfileCard/ProfileActions/index.tsx
  src/features/user/MFV2/PublicProfileLayout/PublicProfileLayout.module.scss
  src/features/user/MFV2/PublicProfileLayout/index.tsx
Labels: MyForest 2.0

#2125 Feedback for My Forest V2
  package-lock.json
  package.json
  public/assets/images/ProfilePageIcons/index.tsx
  public/assets/images/profile-bg-image.png
  public/assets/images/profileBackground.jpg
  public/static/locales/en/editProfile.json
  public/static/locales/en/profile.json
  src/features/common/Layout/CustomTooltip/index.tsx
  src/features/common/WebappButton/WebappButton.module.scss
  src/features/common/WebappButton/index.tsx
  src/features/user/MFV2/CommunityContributions/CustomTooltip.tsx
  src/features/user/MFV2/CommunityContributions/index.tsx
  src/features/user/MFV2/ContributionsMap/Common/common.module.scss
  src/features/user/MFV2/ForestProgress/ForestProgress.module.scss
  src/features/user/MFV2/ForestProgress/TargetFormInput.tsx
  src/features/user/MFV2/ProfileCard/ProfileCard.module.scss
  src/features/user/MFV2/ProfileCard/index.tsx
  src/features/user/MFV2/ProfileLayout/ProfileLayout.module.scss
  src/features/user/MFV2/PublicProfileLayout/PublicProfileLayout.module.scss
  src/features/user/MFV2/PublicProfileLayout/index.tsx
  src/features/user/Settings/EditProfile/EditProfileForm.tsx
  src/theme/global.scss
Labels: PR: reviewed-approved, MyForest 2.0

#2131 Fix name wrapping in profile
  public/assets/images/icons/myForestMapIcons/ClusterMarkerIcons.tsx
  public/assets/images/icons/myForestMapIcons/PointMarkerIcons.tsx
  public/static/locales/en/profile.json
  src/features/common/Layout/MyForestContextV2.tsx
  src/features/user/MFV2/CommunityContributions/NoContributions.tsx
  src/features/user/MFV2/MyContributions/MyContributions.module.scss
  src/features/user/MFV2/ProfileCard/ProfileActions/index.tsx
  src/features/user/MFV2/ProfileCard/ProfileCard.module.scss
  src/features/user/MFV2/ProfileLayout/ProfileLayout.module.scss
  src/features/user/MFV2/PublicProfileLayout/PublicProfileLayout.module.scss
Labels: PR: reviewed-approved, MyForest 2.0

#2128 Feature/link-mfv2
  pages/sites/[slug]/[locale]/profile/index.tsx
  pages/sites/[slug]/[locale]/profile/mfv1.tsx
  pages/sites/[slug]/[locale]/profile/mfv2.tsx
  pages/sites/[slug]/[locale]/public/[id].tsx
  pages/sites/[slug]/[locale]/t/[profile].tsx
  src/features/user/Settings/EditProfile/EditProfileForm.tsx
Labels: PR: reviewed-approved, MyForest 2.0

#2137 Resolves chromatic build issue due to missing env var
  .github/workflows/chromatic.yml
  .storybook/main.js
  .storybook/preview.js
  pages/api/data-explorer/map/distinct-species/[projectId].ts
  pages/api/data-explorer/map/sites/[projectId].ts
  pages/api/data-explorer/species-planted.ts
  pages/api/data-explorer/total-species-planted.ts
  pages/api/data-explorer/total-trees-planted.ts
  pages/api/data-explorer/trees-planted.ts
  src/redis-client.ts
  src/theme/theme.ts
  src/utils/multiTenancy/helpers.ts
Labels: PR: reviewed-approved, MyForest 2.0

#2127 feat: add rich text transaltion
  public/static/locales/en/manageProjects.json
  public/static/locales/en/me.json
  public/static/locales/en/planetcash.json
  src/features/user/Account/components/AccountRecord.tsx
  src/features/user/ManageProjects/StepForm.module.scss
  src/features/user/ManageProjects/index.tsx
  src/features/user/PlanetCash/components/AccountDetails.tsx
  src/features/user/PlanetCash/components/CreateAccountForm.tsx
Labels: PR: reviewed-approved

#2129 Fixes loss of embed state when project details page loads
  pages/sites/[slug]/[locale]/[p].tsx
Labels: PR: reviewed-approved

#2141 Release Small Fixes
  package-lock.json
  pages/sites/[slug]/[locale]/[p].tsx
  public/static/locales/cs/manageProjects.json
  public/static/locales/de/manageProjects.json
  public/static/locales/de/me.json
  public/static/locales/de/planetcash.json
  public/static/locales/en/manageProjects.json
  public/static/locales/en/me.json
  public/static/locales/en/planetcash.json
  public/static/locales/es/manageProjects.json
  public/static/locales/fr/manageProjects.json
  public/static/locales/it/manageProjects.json
  public/static/locales/pt-BR/manageProjects.json
  src/features/user/Account/components/AccountRecord.tsx
  src/features/user/ManageProjects/StepForm.module.scss
  src/features/user/ManageProjects/index.tsx
  src/features/user/PlanetCash/components/AccountDetails.tsx
  src/features/user/PlanetCash/components/CreateAccountForm.tsx
Labels: PR: reviewed-approved

#2146 hotfix: hide website button if url is missing
  src/features/user/MFV2/ProfileCard/ProfileActions/index.tsx
Labels: PR: reviewed-approved

#2148 Feature/storybook folder structure
  .github/workflows/chromatic.yml
  src/temp/stories/common/InfoIconPopup.stories.tsx
  src/temp/stories/common/ProjectBadge.stories.tsx
  src/temp/stories/common/Reports.stories.tsx
  src/temp/stories/landingPage/ExploreProject.stories.tsx
  src/temp/stories/projectDetails/About.stories.tsx
  src/temp/stories/projectDetails/AdditionalInfo.stories.tsx
  src/temp/stories/projectDetails/Contacts.stories.tsx
  src/temp/stories/projectDetails/FirePopup.stories.tsx
  src/temp/stories/projectDetails/ImagesSlider.stories.tsx
  src/temp/stories/projectDetails/KeyInfo.stories.tsx
  src/temp/stories/projectDetails/MapPreview.stories.tsx
  src/temp/stories/projectDetails/ProjectDownloads.stories.tsx
  src/temp/stories/projectDetails/SingleMapTab.stories.tsx
  src/temp/stories/projectDetails/Sites.stories.tsx
  src/temp/stories/projectDetails/Tabs.stories.tsx
  src/temp/stories/projectDetails/TimeTravelDropdown.stories.tsx
  src/temp/stories/projectDetails/VideoPlayer.stories.tsx
Labels: PR: reviewed-approved

#2154 Projects redesign/basic mobile structure
  pages/sites/[slug]/[locale]/prd/[p].tsx
  pages/sites/[slug]/[locale]/prd/index.tsx
  src/features/common/Layout/ProjectsLayout/MobileProjectsLayout.tsx
  src/features/common/Layout/ProjectsLayout/ProjectsLayout.module.scss
Labels: PR: reviewed-approved, projects redesign

#2150 Basic Structure for Redesigned Pages
  pages/_app.tsx
  pages/sites/[slug]/[locale]/prd/[p].tsx
  pages/sites/[slug]/[locale]/prd/index.tsx
  src/features/common/Layout/ProjectsLayout/MobileProjectsLayout.tsx
  src/features/common/Layout/ProjectsLayout/ProjectsLayout.module.scss
  src/features/common/Layout/ProjectsLayout/ProjectsMap.tsx
  src/features/common/Layout/ProjectsLayout/index.tsx
Labels: PR: unreviewed, projects redesign

#2160 Release Fix Profile Contributions Restrictions and Theme Color
  src/features/common/InputTypes/NewToggleSwitch.tsx
  src/features/user/MFV2/ContributionsMap/Markers/ProjectTypeIcon.tsx
  src/server/procedures/myForestV2/contributions.ts
  src/utils/myForestV2Utils.ts
Labels: PR: reviewed-approved

#2156 Projects redesign/project markers
  public/assets/images/icons/myForestMapIcons/PointMarkerIcons.tsx
  src/features/common/Layout/ProjectsLayout/MobileProjectsLayout.tsx
  src/features/common/Layout/ProjectsLayout/ProjectsMap.tsx
  src/features/common/Layout/ProjectsLayout/index.tsx
  src/features/common/types/projectv2.d.ts
  src/features/projectsV2/ProjectsContext.tsx
  src/features/projectsV2/ProjectsMap/MultipleProjectsView.tsx
  src/features/projectsV2/ProjectsMap/ProjectMarkers/ProjectMarkerIcon.tsx
  src/features/projectsV2/ProjectsMap/ProjectMarkers/ProjectMarkers.module.scss
  src/features/projectsV2/ProjectsMap/ProjectMarkers/SingleMarker.tsx
  src/features/projectsV2/ProjectsMap/ProjectMarkers/index.tsx
  src/features/projectsV2/ProjectsMap/ProjectPopup/ProjectPopup.module.scss
  src/features/projectsV2/ProjectsMap/ProjectPopup/index.tsx
  src/features/projectsV2/ProjectsMap/index.tsx
  src/features/projectsV2/ProjectsMap/utils.tsx
  src/features/projectsV2/ProjectsMapContext.tsx
  src/theme/themeProperties.ts
Labels: PR: reviewed-approved, projects redesign

#2158 Render list of projects on the landing page
  package-lock.json
  package.json
  pages/sites/[slug]/[locale]/prd/[p].tsx
  pages/sites/[slug]/[locale]/prd/index.tsx
  pages/sites/[slug]/[locale]/t/[profile].tsx
  public/assets/images/icons/projectV2/FieldReviewedIcon.tsx
  public/assets/images/icons/projectV2/NewInfoIcon.tsx
  public/assets/images/icons/projectV2/OffSiteReviewedIcon.tsx
  public/assets/images/icons/projectV2/TopProjectIcon.tsx
  public/static/locales/en/allProjects.json
  public/static/locales/en/manageProjects.json
  public/static/locales/en/projectDetails.json
  src/features/common/Layout/CustomTooltip/index.tsx
  src/features/common/Layout/ProjectsLayout/ProjectsLayout.module.scss
  src/features/common/types/ProjectPropsContextInterface.ts
  src/features/common/types/projectv2.d.ts
  src/features/projects/components/PopupProject.tsx
  src/features/projects/components/ProjectSnippet.tsx
  src/features/projects/components/VerifiedBadge.tsx
  src/features/projects/components/maps/Markers.tsx
  src/features/projects/components/projectDetails/TopProjectReports.tsx
  src/features/projects/screens/Projects.tsx
  src/features/projects/screens/SingleProjectDetails.tsx
  src/features/projects/styles/Projects.scss
  src/features/projectsV2/ProjectsMap/utils.tsx
  src/features/projectsV2/ProjectsSection.tsx
  src/features/projectsV2/components/ProjectSnippet.tsx
  src/features/projectsV2/components/microComponents/ImageSection.tsx
  src/features/projectsV2/components/microComponents/ProjectBadge.tsx
  src/features/projectsV2/components/microComponents/ProjectInfoSection.tsx
  src/features/projectsV2/components/microComponents/ProjectTypeIcon.tsx
  src/features/projectsV2/stories/common/ProjectBadge.stories.tsx
  src/features/projectsV2/styles/Badge.module.scss
  src/features/projectsV2/styles/ProjectSnippet.module.scss
  src/features/projectsV2/styles/ProjectsSection.module.scss
  src/features/user/MFV2/CommunityContributions/index.tsx
  src/features/user/MFV2/MyContributions/ProjectHeader.tsx
  src/features/user/MFV2/TpoProjects/index.tsx
  src/features/user/Profile/components/MyContributions/microComponents/ProjectsContainer.tsx
  src/features/user/Settings/EditProfile/EditProfileForm.tsx
  src/temp/ProjectBadge/Badge.module.scss
  src/temp/ProjectBadge/ProjectBadge.tsx
  src/temp/components/InfoIconPopup.tsx
  src/temp/icons/FieldReviewedIcon.tsx
  src/temp/icons/NewInfoIcon.tsx
  src/temp/icons/OffSiteReviewedIcon.tsx
  src/temp/icons/TopProjectIcon.tsx
  src/theme/_colors.scss
  src/theme/theme.ts
  src/theme/themeProperties.ts
Labels: PR: reviewed-approved, projects redesign
