Repository Plant-for-the-Planet-org/planet-webapp, pull requests merged in 2024-09, with the labels that each got.

#2208 Update webapp to adapt for new plant locations API
  pages/api/data-explorer/export.ts
  pages/api/data-explorer/map/distinct-species/[projectId].ts
  pages/api/data-explorer/map/plant-location/[plantLocationId].ts
  pages/api/data-explorer/map/plant-location/index.ts
  pages/api/data-explorer/species-planted.ts
  pages/api/data-explorer/total-species-planted.ts
  pages/api/data-explorer/total-trees-planted.ts
  pages/api/data-explorer/trees-planted.ts
  src/features/common/Layout/ProjectPropsContext.tsx
  src/features/common/types/dataExplorer.d.ts
  src/features/common/types/plantLocation.d.ts
  src/features/projects/components/PlantLocation/PlantLocationDetails.tsx
  src/features/projects/components/maps/PlantLocations.tsx
  src/features/projects/components/maps/Project.tsx
  src/features/user/TreeMapper/Analytics/components/Map/index.tsx
  src/features/user/TreeMapper/Import/components/PlantingLocation.tsx
  src/features/user/TreeMapper/Import/components/ReviewSubmit.tsx
  src/features/user/TreeMapper/Import/components/SampleTreeCard.tsx
  src/features/user/TreeMapper/Import/components/SampleTrees.tsx
  src/features/user/TreeMapper/Import/index.tsx
  src/features/user/TreeMapper/components/Map.tsx
  src/features/user/TreeMapper/components/PlantLocation.tsx
  src/features/user/TreeMapper/components/PlantLocationPage.tsx
  src/features/user/TreeMapper/components/TreeMapperList.tsx
  src/features/user/TreeMapper/index.tsx
  src/utils/maps/plantLocations.ts
Labels: PR: reviewed-approved

#2210 Release Fix plantLocations API changes
  pages/api/data-explorer/export.ts
  pages/api/data-explorer/map/distinct-species/[projectId].ts
  pages/api/data-explorer/map/plant-location/[plantLocationId].ts
  pages/api/data-explorer/map/plant-location/index.ts
  pages/api/data-explorer/species-planted.ts
  pages/api/data-explorer/total-species-planted.ts
  pages/api/data-explorer/total-trees-planted.ts
  pages/api/data-explorer/trees-planted.ts
  src/features/common/Layout/ProjectPropsContext.tsx
  src/features/common/types/dataExplorer.d.ts
  src/features/common/types/plantLocation.d.ts
  src/features/projects/components/PlantLocation/PlantLocationDetails.tsx
  src/features/projects/components/maps/PlantLocations.tsx
  src/features/projects/components/maps/Project.tsx
  src/features/user/TreeMapper/Analytics/components/Map/index.tsx
  src/features/user/TreeMapper/Import/components/PlantingLocation.tsx
  src/features/user/TreeMapper/Import/components/ReviewSubmit.tsx
  src/features/user/TreeMapper/Import/components/SampleTreeCard.tsx
  src/features/user/TreeMapper/Import/components/SampleTrees.tsx
  src/features/user/TreeMapper/Import/index.tsx
  src/features/user/TreeMapper/components/Map.tsx
  src/features/user/TreeMapper/components/PlantLocation.tsx
  src/features/user/TreeMapper/components/PlantLocationPage.tsx
  src/features/user/TreeMapper/components/TreeMapperList.tsx
  src/features/user/TreeMapper/index.tsx
  src/utils/maps/plantLocations.ts
Labels: PR: reviewed-approved

#2164 Projects redesign - Map Feature Explorer
  public/assets/images/icons/projectV2/ExploreIcon.tsx
  public/assets/images/icons/projectV2/InfoIcon.tsx
  public/assets/images/icons/projectV2/PlayIcon.tsx
  src/features/common/Layout/ProjectsLayout/ProjectsLayout.module.scss
  src/features/common/Layout/ProjectsLayout/index.tsx
  src/features/projectsV2/ProjectsMap/MapFeatureExplorer/CustomButton.tsx
  src/features/projectsV2/ProjectsMap/MapFeatureExplorer/CustomSlider.tsx
  src/features/projectsV2/ProjectsMap/MapFeatureExplorer/CustomSwitch.tsx
  src/features/projectsV2/ProjectsMap/MapFeatureExplorer/MapFeatureExplorer.module.scss
  src/features/projectsV2/ProjectsMap/MapFeatureExplorer/MapSettings.tsx
  src/features/projectsV2/ProjectsMap/MapFeatureExplorer/index.tsx
  src/features/projectsV2/ProjectsMap/index.tsx
  src/features/projectsV2/ProjectsMap/stories/MapFeatureExplorer.stories.tsx
  src/features/projectsV2/ProjectsMapContext.tsx
  src/temp/Explore/MapLayerOptions.tsx
  src/temp/stories/landingPage/ExploreProject.stories.tsx
Labels: PR: reviewed-approved

#2213 Implement mobile UI for MapFeatureExplorer
  public/assets/images/icons/projectV2/ExploreIcon.tsx
  src/features/common/Layout/ProjectsLayout/ProjectsLayout.module.scss
  src/features/common/Layout/ProjectsLayout/index.tsx
  src/features/projectsV2/ProjectListControls/ProjectListControlForMobile.tsx
  src/features/projectsV2/ProjectListControls/microComponents/ProjectSearchAndFilter.tsx
  src/features/projectsV2/ProjectListControls/microComponents/ViewModeTabs.tsx
  src/features/projectsV2/ProjectListControls/styles/ProjectListControls.module.scss
  src/features/projectsV2/ProjectsMap/MapFeatureExplorer/CustomButton.tsx
  src/features/projectsV2/ProjectsMap/MapFeatureExplorer/MapFeatureExplorer.module.scss
  src/features/projectsV2/ProjectsMap/MapFeatureExplorer/index.tsx
  src/features/projectsV2/ProjectsMap/index.tsx
  src/features/projectsV2/ProjectsMapContext.tsx
Labels: PR: unreviewed

#2220 Release Language and Currency Related Updates
  package-lock.json
  package.json
  pages/_app.tsx
  public/static/locales/de/manageProjects.json
  public/static/locales/de/me.json
  public/static/locales/en/me.json
  src/features/common/Layout/CurrencyContext.tsx
  src/features/common/Layout/Footer/SelectLanguageAndCountry.tsx
  src/utils/countryCurrency/countryUtils.js
Labels: PR: reviewed-approved

#2228 Release bump path-to-regexp and express
  package-lock.json
  package.json
Labels: PR: reviewed-approved

#2231 Add missing translations
  .gitignore
  .vscode/tasks.json
  pages/sites/[slug]/[locale]/profile/redeem/[code].tsx
  public/static/locales/en/me.json
  src/features/user/ManageProjects/components/BasicDetails.tsx
Labels: PR: unreviewed

#2232 Release Fix Translations
  .gitignore
  .vscode/tasks.json
  pages/sites/[slug]/[locale]/profile/redeem/[code].tsx
  public/static/locales/de/me.json
  public/static/locales/en/me.json
  src/features/user/ManageProjects/components/BasicDetails.tsx
Labels: PR: unreviewed

#2236 [Snyk] Security upgrade next from 13.5.6 to 13.5.7
  package-lock.json
  package.json
Labels: Next in line

#2238 Release: update next.js to 13.5.7
  package-lock.json
  package.json
Labels: PR: reviewed-approved

#2199 Refactor useEffect logic to simplify impersonation mode check
  src/features/common/Layout/UserPropsContext.tsx
Labels: PR: reviewed-approved

#2239 Add prefill functionality for impersonation form
  src/features/user/BulkCodes/components/AddRecipient.tsx
  src/features/user/Settings/ImpersonateUser/ImpersonateUserForm.tsx
Labels: PR: reviewed-approved

#2240 Release: updates to impersonation feature
  src/features/common/Layout/UserPropsContext.tsx
  src/features/user/BulkCodes/components/AddRecipient.tsx
  src/features/user/Settings/ImpersonateUser/ImpersonateUserForm.tsx
Labels: PR: reviewed-approved

#2209 Projects redesign/zoom into site
  pages/sites/[slug]/[locale]/[p].tsx
  src/features/common/Layout/ProjectsLayout/index.tsx
  src/features/projectsV2/ProjectDetails/index.tsx
  src/features/projectsV2/ProjectListControls/ProjectListControlForMobile.tsx
  src/features/projectsV2/ProjectListControls/index.tsx
  src/features/projectsV2/ProjectListControls/microComponents/ClassificationDropDown.tsx
  src/features/projectsV2/ProjectListControls/utils.tsx
  src/features/projectsV2/ProjectSnippet/index.tsx
  src/features/projectsV2/ProjectSnippet/microComponents/ImageSection.tsx
  src/features/projectsV2/ProjectsContext.tsx
  src/features/projectsV2/ProjectsMap/MapControls.tsx
  src/features/projectsV2/ProjectsMap/MultipleProjectsView.tsx
  src/features/projectsV2/ProjectsMap/ProjectMarkers/ProjectMarkerIcon.tsx
  src/features/projectsV2/ProjectsMap/ProjectSiteDropDown/ProjectSiteList.tsx
  src/features/projectsV2/ProjectsMap/ProjectSiteDropDown/SiteDropdown.module.scss
  src/features/projectsV2/ProjectsMap/ProjectSiteDropDown/index.tsx
  src/features/projectsV2/ProjectsMap/ProjectsMap.module.scss
  src/features/projectsV2/ProjectsMap/SingleProjectView.tsx
  src/features/projectsV2/ProjectsMap/index.tsx
  src/features/projectsV2/ProjectsMap/microComponents/MobileControls.tsx
  src/features/projectsV2/ProjectsMap/microComponents/SatelliteLayer.tsx
  src/features/projectsV2/ProjectsMap/microComponents/SitePolygon.tsx
  src/features/projectsV2/ProjectsMap/stories/ProjectSiteDropdown.stories.tsx
  src/features/projectsV2/ProjectsMap/utils.tsx
  src/features/projectsV2/ProjectsMapContext.tsx
  src/temp/ProjectSiteDropdown/SiteDropdown.module.scss
  src/temp/ProjectSiteDropdown/index.tsx
  src/temp/stories/projectDetails/Sites.stories.tsx
  src/utils/mapsV2/zoomToProjectSite.ts
  src/utils/projectV2.ts
Labels: PR: reviewed-approved, projects redesign

#2244 [Snyk] Upgrade react-hook-form from 7.52.2 to 7.53.0
  package-lock.json
  package.json
Labels: dependencies, PR: reviewed-approved

#2242 [Snyk] Upgrade next-intl from 3.17.6 to 3.19.1
  i18n.ts
  package-lock.json
  package.json
Labels: dependencies, PR: reviewed-approved

#2243 [Snyk] Upgrade apexcharts from 3.52.0 to 3.53.0
  package-lock.json
  package.json
Labels: dependencies, PR: reviewed-approved

#2246 Fix tooltip translation bug and update package-lock
  package-lock.json
  pages/api/data-explorer/map/plant-location/index.ts
  src/features/user/TreeMapper/Analytics/components/SpeciesPlanted/Tooltip/index.tsx
  src/features/user/TreeMapper/Analytics/components/SpeciesPlanted/index.tsx
  src/features/user/TreeMapper/Analytics/components/TreePlanted/Tooltip/index.tsx
  src/features/user/TreeMapper/Analytics/components/TreePlanted/index.tsx
Labels: PR: unreviewed
