Repository Plant-for-the-Planet-org/planet-webapp, pull requests merged in 2024-08, with the labels that each got.

#2162 Updates paymentOptions API call for Bulk Codes
  pages/sites/[slug]/[locale]/profile/bulk-codes/[method]/[id].tsx
  src/features/user/BulkCodes/components/ProjectSelector.tsx
Labels: PR: reviewed-approved

#2054 refactor navbar and minor change in styling
  package-lock.json
  package.json
  pages/sites/[slug]/[locale]/home.tsx
  public/assets/images/icons/headerIcons/DefaultProfileImageIcon.tsx
  public/assets/images/navigation/Donate.tsx
  public/assets/images/navigation/DonateSelected.tsx
  public/assets/images/navigation/Globe.tsx
  public/assets/images/navigation/GlobeSelected.tsx
  public/assets/images/navigation/HomeLogoSelected.tsx
  public/assets/images/navigation/HomoLogo.tsx
  public/assets/images/navigation/Leaderboard.tsx
  public/assets/images/navigation/LeaderboardSelected.tsx
  public/assets/images/navigation/Leaf.tsx
  public/assets/images/navigation/LeafSelected.tsx
  public/assets/images/navigation/Me.tsx
  public/assets/images/navigation/MeSelected.tsx
  public/assets/images/navigation/OceanforceChallengeIcon.tsx
  public/assets/images/navigation/ShopIcon.tsx
  public/assets/images/navigation/VTOChallengeIcon.tsx
  public/static/locales/en/common.json
  src/features/common/Layout/Navbar/Navbar.scss
  src/features/common/Layout/Navbar/getNavBarIcon.tsx
  src/features/common/Layout/Navbar/getSubMenu.tsx
  src/features/common/Layout/Navbar/index.tsx
  src/features/common/Layout/Navbar/microComponents/BrandLogo.tsx
  src/features/common/Layout/Navbar/microComponents/NavigationItem.tsx
  src/features/common/Layout/Navbar/microComponents/NavigationMenu.tsx
  src/features/common/Layout/Navbar/microComponents/PlanetLogo.tsx
  src/features/common/Layout/Navbar/microComponents/SecondaryLogo.tsx
  src/features/common/Layout/Navbar/microComponents/SignInButton.tsx
  src/features/common/Layout/Navbar/microComponents/SubMenu.tsx
  src/features/common/Layout/Navbar/microComponents/UserProfileButton.tsx
  src/features/common/Layout/UserLayout/UserLayout.module.scss
  src/features/projects/styles/Filters.module.scss
  src/theme/global.scss
  src/utils/multiTenancy/helpers.ts
  src/utils/navbarUtils.ts
  tenant.config.ts
Labels: PR: reviewed-approved

#2166 Remove references to treecounter/treecounter groups from profile apis
  prisma/schema.prisma
  src/features/common/Layout/MyForestContextV2.tsx
  src/features/common/types/myForestv2.d.ts
  src/server/procedures/myForestV2/contributions.ts
  src/server/procedures/myForestV2/leaderboard.ts
  src/server/utils/fetchGroupTreecounterData.ts
  src/server/utils/fetchProfile.ts
  src/server/utils/fetchProfileGroupData.ts
Labels: PR: unreviewed

#2175 [Snyk] Upgrade next-intl from 3.17.1 to 3.17.2
  package-lock.json
  package.json
Labels: dependencies, PR: reviewed-approved

#2176 Release August 12th, 2024
  package-lock.json
  package.json
  prisma/schema.prisma
  src/features/common/Layout/MyForestContextV2.tsx
  src/features/common/types/myForestv2.d.ts
  src/server/procedures/myForestV2/contributions.ts
  src/server/procedures/myForestV2/leaderboard.ts
  src/server/utils/fetchGroupTreecounterData.ts
  src/server/utils/fetchProfile.ts
  src/server/utils/fetchProfileGroupData.ts
Labels: PR: reviewed-approved

#2190 Updates to Payment History/Subscriptions for Composite Donations
  public/static/locales/en/me.json
  src/features/common/types/payments.d.ts
  src/features/user/Account/components/AccountRecord.tsx
  src/features/user/Account/components/Certificates.tsx
  src/features/user/Account/components/RecurrencyRecord.tsx
Labels: PR: reviewed-approved

#2188 Update planet-sdk and refactor code to get targets from user.scores
  package-lock.json
  package.json
  src/features/user/MFV2/ForestProgress/TargetsModal.tsx
  src/features/user/MFV2/ProfileLayout/index.tsx
  src/features/user/MFV2/PublicProfileLayout/index.tsx
  src/features/user/MFV2/stories/ProfileActions.stories.tsx
  src/features/user/MFV2/stories/ProfileCard.stories.tsx
Labels: PR: reviewed-approved

#2194 Remove unused axios dependency
  package-lock.json
  package.json
Labels: PR: reviewed-approved

#2191 Release Fixes Recurrencies and Scores
  package-lock.json
  package.json
  public/static/locales/en/me.json
  src/features/common/types/payments.d.ts
  src/features/user/Account/components/AccountRecord.tsx
  src/features/user/Account/components/Certificates.tsx
  src/features/user/Account/components/RecurrencyRecord.tsx
  src/features/user/MFV2/ForestProgress/TargetsModal.tsx
  src/features/user/MFV2/ProfileLayout/index.tsx
  src/features/user/MFV2/PublicProfileLayout/index.tsx
  src/features/user/MFV2/stories/ProfileActions.stories.tsx
  src/features/user/MFV2/stories/ProfileCard.stories.tsx
Labels: PR: reviewed-approved

#2195 Update @emotion dependencies
  package-lock.json
  package.json
Labels: PR: reviewed-approved

#2205 Release: bump webpack and babel-loader
  package-lock.json
  package.json
Labels: PR: reviewed-approved

#2197 changed appDomain for default tenant
  package-lock.json
  package.json
  tenant.config.ts
Labels: PR: reviewed-approved, PR: draft

#2196 feat: render project snippet as a popup
  src/features/common/Layout/CustomTooltip/index.tsx
  src/features/projects/screens/SingleProjectDetails.tsx
  src/features/projectsV2/ProjectList/index.tsx
  src/features/projectsV2/ProjectSnippet/index.tsx
  src/features/projectsV2/ProjectSnippet/microComponents/ImageSection.tsx
  src/features/projectsV2/ProjectSnippet/microComponents/ProjectBadge.tsx
  src/features/projectsV2/ProjectSnippet/styles/ProjectSnippet.module.scss
  src/features/projectsV2/ProjectsMap/ProjectPopup/ProjectPopup.module.scss
  src/features/projectsV2/ProjectsMap/ProjectPopup/index.tsx
  src/features/user/MFV2/CommunityContributions/index.tsx
  src/features/user/MFV2/TpoProjects/index.tsx
  src/features/user/Profile/components/MyContributions/microComponents/ProjectsContainer.tsx
  src/features/user/Settings/EditProfile/EditProfileForm.tsx
Labels: PR: reviewed-approved
