Repository Plant-for-the-Planet-org/planet-webapp, pull requests merged in 2025-07, with the labels that each got.

#2344 fix: show correct unit type for manage projects list screen
  public/static/locales/en/common.json
  src/features/user/ManageProjects/ProjectsContainer.tsx
Labels: PR: reviewed-approved

#2583 Hotfix/unify date picker styles
  cspell.json
  src/features/user/Account/CancelModal.tsx
  src/features/user/Account/EditModal.tsx
  src/features/user/Account/PauseModal.tsx
  src/features/user/ManageProjects/components/DetailedAnalysis.tsx
  src/features/user/ManageProjects/components/ProjectCertificates.tsx
  src/features/user/ManageProjects/components/ProjectSpending.tsx
  src/features/user/RegisterTrees/RegisterTreesWidget.tsx
  src/features/user/TreeMapper/Analytics/components/Export/index.tsx
  src/features/user/TreeMapper/Analytics/components/ProjectFilter/index.tsx
  src/features/user/TreeMapper/Import/components/PlantingLocation.tsx
  src/features/user/TreeMapper/Import/components/SampleTreeCard.tsx
  src/theme/themeStyles.ts
Labels: PR: reviewed-approved

#2528 Implement dropdown functionality and UI updates for SiteMapLayerControls
  .github/workflows/chromatic.yml
  .storybook/preview.js
  public/assets/images/icons/projectV2/AverageMarkerIcon.tsx
  public/assets/images/icons/projectV2/BiomassChangeIcon.tsx
  public/assets/images/icons/projectV2/DropdownDownArrow.tsx
  public/assets/images/icons/projectV2/TreeCoverIcon.tsx
  src/features/common/Layout/Navbar/microComponents/Archive/NavigationItem.tsx
  src/features/projectsV2/ProjectsMap/SiteMapLayerControls/AverageIndicator.tsx
  src/features/projectsV2/ProjectsMap/SiteMapLayerControls/LayerInfoPopup.tsx
  src/features/projectsV2/ProjectsMap/SiteMapLayerControls/LayerInfoTooltip.tsx
  src/features/projectsV2/ProjectsMap/SiteMapLayerControls/PercentLegend.tsx
  src/features/projectsV2/ProjectsMap/SiteMapLayerControls/RangeLegend.tsx
  src/features/projectsV2/ProjectsMap/SiteMapLayerControls/SiteLayerDropdown.tsx
  src/features/projectsV2/ProjectsMap/SiteMapLayerControls/SiteLayerInfo.tsx
  src/features/projectsV2/ProjectsMap/SiteMapLayerControls/SiteLayerLegend.tsx
  src/features/projectsV2/ProjectsMap/SiteMapLayerControls/SiteLayerOptions.tsx
  src/features/projectsV2/ProjectsMap/SiteMapLayerControls/SiteLayerSelector.tsx
  src/features/projectsV2/ProjectsMap/SiteMapLayerControls/SiteMapLayerControls.module.scss
  src/features/projectsV2/ProjectsMap/SiteMapLayerControls/index.tsx
  src/features/projectsV2/ProjectsMap/stories/SiteMapLayerControls.stories.tsx
  src/theme/_colors.scss
  src/theme/theme.ts
Labels: PR: reviewed-approved, remote sensing

#2590 Refactor style imports for consistency
  src/features/projectsV2/ProjectDetails/components/MapPreview.tsx
  src/features/projectsV2/ProjectDetails/components/microComponents/ShowMapButton.tsx
  src/features/user/Profile/ContributionsMap/Common/ContributionStats.tsx
  src/features/user/Profile/ContributionsMap/Markers/DonationClusterMarker.tsx
  src/features/user/Profile/ContributionsMap/Markers/PointMarkers.tsx
  src/features/user/Profile/ContributionsMap/Markers/RegisteredTreeClusterMarker.tsx
  src/features/user/Profile/ContributionsMap/Popup/DonationPopup.tsx
  src/features/user/Profile/ContributionsMap/Popup/PopupImageSection.tsx
  src/features/user/Profile/ContributionsMap/Popup/ProjectInfoSection.tsx
  src/features/user/Profile/ContributionsMap/Popup/RegisteredTreesPopup.tsx
  src/features/user/Profile/ContributionsMap/index.tsx
Labels: PR: reviewed-approved

#2584 refactor(manage-project): use design system colors
  src/features/user/ManageProjects/ProjectsContainer.module.scss
  src/features/user/ManageProjects/StepForm.module.scss
  src/features/user/ManageProjects/components/BasicDetails.tsx
  src/features/user/ManageProjects/components/DetailedAnalysis.tsx
  src/features/user/ManageProjects/components/ProjectSelection.tsx
  src/features/user/ManageProjects/components/ProjectSites.tsx
  src/theme/global.scss
Labels: PR: reviewed-approved

#2593 Rationalizes colors for User Layout (Sidebar for dashboard)
  cspell.json
  src/features/common/Layout/UserLayout/UserLayout.module.scss
  src/features/common/Layout/UserLayout/UserLayout.tsx
  src/features/user/Settings/ImpersonateUser/SupportPin.tsx
Labels: PR: reviewed-approved

#2594 refactor: add early return for null plantLocationInfo and remove redu…
  package-lock.json
  package.json
  src/features/projectsV2/ProjectDetails/components/OtherInterventionInfo.tsx
  src/features/projectsV2/ProjectDetails/components/microComponents/InterventionHeader.tsx
  src/utils/constants/intervention.ts
Labels: PR: reviewed-approved

#2592 refactor(tree-mapper): replace color codes with design system color c…
  src/features/user/TreeMapper/Analytics/components/Container/index.module.scss
  src/features/user/TreeMapper/Analytics/components/Counter/components/CounterItem/index.module.scss
  src/features/user/TreeMapper/Analytics/components/Counter/index.module.scss
  src/features/user/TreeMapper/Analytics/components/Export/index.tsx
  src/features/user/TreeMapper/Analytics/components/Map/components/PlantLocationDetails/index.module.scss
  src/features/user/TreeMapper/Analytics/components/Map/components/PlantLocationDetails/index.tsx
  src/features/user/TreeMapper/Analytics/components/Map/components/TreeMapperIcon.tsx
  src/features/user/TreeMapper/Analytics/components/Map/index.module.scss
  src/features/user/TreeMapper/Analytics/components/Map/index.tsx
  src/features/user/TreeMapper/Analytics/components/ProjectFilter/index.tsx
  src/features/user/TreeMapper/Analytics/components/SpeciesPlanted/Tooltip/index.module.scss
  src/features/user/TreeMapper/Analytics/components/SpeciesPlanted/index.tsx
  src/features/user/TreeMapper/Analytics/components/TreePlanted/Tooltip/index.module.scss
  src/features/user/TreeMapper/Analytics/components/TreePlanted/index.tsx
  src/features/user/TreeMapper/Import/Import.module.scss
  src/features/user/TreeMapper/Import/components/MapComponent.tsx
  src/features/user/TreeMapper/Import/components/SampleTrees.tsx
  src/features/user/TreeMapper/Import/index.tsx
  src/features/user/TreeMapper/MySpecies/MySpecies.module.scss
  src/features/user/TreeMapper/TreeMapper.module.scss
  src/features/user/TreeMapper/components/Map.tsx
  src/theme/_colors.scss
  src/theme/theme.ts
  src/theme/themeProperties.ts
Labels: PR: reviewed-approved

#2600 [Snyk] Upgrade @tanstack/react-query from 5.80.7 to 5.81.2
  package-lock.json
  package.json
Labels: PR: reviewed-approved

#2597 refactor(manage-project): replace old MUI Switch with new custom Togg…
  src/features/common/InputTypes/NewToggleSwitch.tsx
  src/features/user/ManageProjects/StepForm.module.scss
  src/features/user/ManageProjects/components/BasicDetails.tsx
  src/features/user/ManageProjects/components/ProjectCertificates.tsx
  src/features/user/ManageProjects/components/SubmitForReview.tsx
Labels: PR: reviewed-approved

#2605 Multi Plant Location - update area display logic and improve type safety
  public/static/locales/de/projectDetails.json
  public/static/locales/en/projectDetails.json
  src/features/common/types/plantLocation.d.ts
  src/features/projectsV2/ProjectDetails/components/MultiPlantLocationInfo.tsx
  src/features/projectsV2/ProjectDetails/components/microComponents/PlantLocationHeader.tsx
  src/features/projectsV2/ProjectDetails/index.tsx
Labels: PR: reviewed-approved

#2599 refactor(api): clean up ApiConfig types for better clarity
  src/features/user/Settings/ApiKey/ApiKeyForm.tsx
  src/features/user/Settings/ImpersonateUser/SupportPin.tsx
  src/hooks/useApi.ts
Labels: PR: reviewed-approved

#2602 Release 07-17-2025
  package-lock.json
  package.json
  public/static/locales/de/projectDetails.json
  public/static/locales/en/projectDetails.json
  src/features/common/InputTypes/GreenRadio.tsx
  src/features/common/InputTypes/NewToggleSwitch.tsx
  src/features/common/Layout/Footer/SelectLanguageAndCountry.module.scss
  src/features/common/Layout/Footer/SelectLanguageAndCountry.tsx
  src/features/common/Layout/UserLayout/IconContainer.tsx
  src/features/common/Layout/UserLayout/LanguageSwitcher.tsx
  src/features/common/Layout/UserLayout/NavLink.tsx
  src/features/common/Layout/UserLayout/UserLayout.module.scss
  src/features/common/Layout/UserLayout/UserLayout.tsx
  src/features/common/types/plantLocation.d.ts
  src/features/common/types/projectv2.d.ts
  src/features/projectsV2/ProjectDetails/components/MultiPlantLocationInfo.tsx
  src/features/projectsV2/ProjectDetails/components/microComponents/PlantLocationHeader.tsx
  src/features/projectsV2/ProjectDetails/index.tsx
  src/features/projectsV2/ProjectsContext.tsx
  src/features/projectsV2/ProjectsMap/InterventionDropDown/index.tsx
  src/features/projectsV2/ProjectsMap/MapControls.tsx
  src/features/projectsV2/ProjectsMap/ProjectSiteDropDown/ProjectSiteList.tsx
  src/features/projectsV2/ProjectsMap/ProjectSiteDropDown/index.tsx
  src/features/user/ManageProjects/StepForm.module.scss
  src/features/user/ManageProjects/components/BasicDetails.tsx
  src/features/user/ManageProjects/components/ProjectCertificates.tsx
  src/features/user/ManageProjects/components/SubmitForReview.tsx
  src/features/user/Settings/ApiKey/ApiKeyForm.tsx
  src/features/user/Settings/ImpersonateUser/SupportPin.tsx
  src/hooks/useApi.ts
Labels: PR: reviewed-approved

#2608 Refactor TimeTravelDropdown open/closed state management
  src/features/projectsV2/ProjectsMap/TimeTravel/index.tsx
  src/features/projectsV2/TimeTravelDropdown/index.tsx
Labels: PR: reviewed-approved

#2541 Enable scroll zoom for the projects map
  src/features/common/Layout/ProjectsLayout/MobileProjectsLayout.tsx
  src/features/common/Layout/ProjectsLayout/index.tsx
  src/features/projectsV2/ProjectsMapContext.tsx
Labels: PR: reviewed-approved

#2613 [Snyk] Upgrade react-hook-form from 7.58.0 to 7.59.0
  package-lock.json
  package.json
Labels: dependencies, PR: reviewed-approved

#2612 [Snyk] Upgrade @tanstack/react-query from 5.81.2 to 5.81.5
  package-lock.json
  package.json
Labels: dependencies, PR: reviewed-approved

#2606 Hotfix/deselect point location
  src/features/projectsV2/ProjectsMap/index.tsx
  src/features/projectsV2/ProjectsMap/microComponents/PlantLocations.tsx
  src/features/projectsV2/ProjectsMap/microComponents/SatelliteLayer.tsx
  src/features/projectsV2/ProjectsMap/microComponents/SitePolygon.tsx
  src/utils/projectV2.ts
Labels: PR: reviewed-approved

#2620 [Snyk] Upgrade react-hook-form from 7.59.0 to 7.60.0
  package-lock.json
  package.json
Labels: PR: reviewed-approved

#2624 Fixes partially hidden mobile swiper for intervention info
  src/features/projectsV2/MobileInfoSwiper/MobileInfoSwiper.module.scss
Labels: PR: reviewed-approved

#2626 Fix Image Slider Autorotate and Empty Image Handling; Refactor ImageCarousel for Manual/Auto Modes
  src/features/common/types/projectv2.d.ts
  src/features/projectsV2/ProjectDetails/components/ImageSlider.tsx
  src/features/projectsV2/ProjectDetails/components/microComponents/ImageCarousel.tsx
  src/features/projectsV2/ProjectDetails/components/microComponents/ImageSliderModal.tsx
Labels: PR: reviewed-approved
