Repository Plant-for-the-Planet-org/planet-webapp, pull requests merged in 2025-06, with the labels that each got.

#2525 chore: upgrade tRPC and TypeScript to latest versions and fix type er…
  package-lock.json
  package.json
  src/utils/trpc.ts
Labels: PR: reviewed-approved

#2545 Hotfix/address action clean up
  src/features/user/Settings/EditProfile/AddressManagement/AddAddress.tsx
  src/features/user/Settings/EditProfile/AddressManagement/DeleteAddress.tsx
  src/features/user/Settings/EditProfile/AddressManagement/EditAddress.tsx
  src/features/user/Settings/EditProfile/AddressManagement/UnsetBillingAddress.tsx
  src/features/user/Settings/EditProfile/AddressManagement/UpdateAddressType.tsx
  src/features/user/Settings/EditProfile/AddressManagement/index.tsx
  src/features/user/Settings/EditProfile/AddressManagement/microComponents/AddressForm.tsx
  src/features/user/Settings/EditProfile/AddressManagement/useAddressOperations.tsx
  src/features/user/Settings/EditProfile/AddressManagement/utils.ts
Labels: PR: reviewed-approved, blocked

#2546 Update profile project type
  package-lock.json
  package.json
  pages/sites/[slug]/[locale]/profile/projects/[id].tsx
  src/features/common/types/map.d.ts
  src/features/common/types/project.d.ts
  src/features/user/ManageProjects/ProjectsContainer.tsx
  src/features/user/ManageProjects/components/BasicDetails.tsx
  src/features/user/ManageProjects/components/DetailedAnalysis.tsx
  src/features/user/ManageProjects/components/ProjectMedia.tsx
  src/features/user/ManageProjects/index.tsx
  src/features/user/RegisterTrees/RegisterTreesWidget.tsx
  src/features/user/TreeMapper/Analytics/index.tsx
  src/features/user/TreeMapper/Import/components/PlantingLocation.tsx
Labels: PR: reviewed-approved

#2564 Use centralized SetState type from common.d.ts
  src/features/common/Layout/BulkCodeContext.tsx
  src/features/user/BulkCodes/components/GenericCodesPartial.tsx
Labels: PR: reviewed-approved

#2566 Rationalize colors for snackbar
  src/features/common/CopyToClipboard/index.tsx
  src/features/common/CustomSnackbar/index.tsx
  src/features/user/CompleteSignup/index.tsx
  src/features/user/Settings/EditProfile/EditProfileForm.tsx
  src/features/user/Widget/EmbedModal.tsx
  src/theme/themeStyles.ts
Labels: PR: unreviewed

#2577 Rationalize colors for CompleteSignup
  src/features/user/CompleteSignup/CompleteSignup.module.scss
  src/features/user/CompleteSignup/index.tsx
Labels: PR: unreviewed

#2579 Fix validation logic in DonationReceiptContext for donor/address changes
  src/features/common/Layout/DonationReceiptContext.tsx
  src/features/user/DonationReceipt/DonorContactManagement.tsx
Labels: PR: reviewed-approved
