Repository Plant-for-the-Planet-org/planet-webapp, pull requests merged in 2025-02, with the labels that each got.

#2398 feat: show total donation value.
  src/features/user/DonationReceipt/DonationReceipt.module.scss
  src/features/user/DonationReceipt/donationReceiptTypes.ts
  src/features/user/DonationReceipt/microComponents/DonationsTable.tsx
  src/features/user/DonationReceipt/microComponents/ReceiptDataSection.tsx
  src/features/user/DonationReceipt/utils.ts
Labels: PR: reviewed-approved

#2395 Adds functionality to show soil bulk density + other available layers in the map
  next.config.js
  public/static/locales/en/maps.json
  src/features/projectsV2/ProjectsMap/ExploreLayers.tsx
  src/features/projectsV2/ProjectsMap/MapFeatureExplorer/microComponents/MapSettingsSection.tsx
  src/features/projectsV2/ProjectsMap/index.tsx
  src/features/projectsV2/ProjectsMapContext.tsx
  src/utils/mapsV2/mapSettings.config.ts
  src/utils/mapsV2/useFetchLayers.ts
Labels: PR: reviewed-changes-requested

#2396 hide filter option condition added
  src/features/projectsV2/ProjectsMap/InterventionDropDown/InterventionList.tsx
  src/features/projectsV2/ProjectsMap/InterventionDropDown/index.tsx
  src/features/projectsV2/ProjectsMap/MapControls.tsx
Labels: PR: reviewed-approved

#2401 feat: Handle error cases for invalid or missing name/address.
  public/assets/images/icons/MissingDataIcon.tsx
  public/static/locales/en/donationReceipt.json
  src/features/user/DonationReceipt/DonationReceipt.module.scss
  src/features/user/DonationReceipt/microComponents/DonorDetails.tsx
  src/features/user/DonationReceipt/microComponents/ReceiptActions.tsx
  src/features/user/DonationReceipt/microComponents/ReceiptDataSection.tsx
Labels: PR: reviewed-approved

#2405 Add maxLength validation for zipCode in forms
  src/features/user/CompleteSignup/index.tsx
  src/features/user/Settings/EditProfile/AddressManagement/microComponents/AddressForm.tsx
Labels: PR: reviewed-approved

#2402 [Snyk] Upgrade @types/geojson from 7946.0.15 to 7946.0.16
  package-lock.json
  package.json
Labels: PR: reviewed-approved

#2404 Add missing payment history statuses
  public/static/locales/en/me.json
Labels: PR: reviewed-approved

#2403 Show single tree plant locations on map and hide irrelevant data in data explorer
  src/features/user/TreeMapper/Analytics/components/Map/components/PlantLocationDetails/index.module.scss
  src/features/user/TreeMapper/Analytics/components/Map/components/PlantLocationDetails/index.tsx
  src/features/user/TreeMapper/Analytics/components/Map/index.tsx
Labels: PR: unreviewed

#2412 Fix TPO profile rendering bug due to class conflicts
  src/features/user/Profile/PublicProfileLayout/index.tsx
Labels: PR: reviewed-approved

#2413 Add X-Locale header to donations POST request
  src/features/user/BulkCodes/forms/IssueCodesForm.tsx
Labels: PR: reviewed-approved

#2408 Fix double locale bug in back navigation
  src/utils/projectV2.ts
Labels: PR: reviewed-changes-requested

#2419 Release Fix Double Locale Bug in Back Navigation
  src/utils/projectV2.ts
Labels: PR: reviewed-approved

#2336 New explore dropdown UI
  next.config.js
  public/static/locales/en/maps.json
  src/features/common/Layout/ProjectsLayout/ProjectsLayout.module.scss
  src/features/common/Layout/ProjectsLayout/index.tsx
  src/features/projectsV2/ProjectListControls/ProjectListControlForMobile.tsx
  src/features/projectsV2/ProjectsMap/ExploreLayers.tsx
  src/features/projectsV2/ProjectsMap/MapFeatureExplorer/CustomButton.tsx
  src/features/projectsV2/ProjectsMap/MapFeatureExplorer/CustomSwitch.tsx
  src/features/projectsV2/ProjectsMap/MapFeatureExplorer/MapFeatureExplorer.module.scss
  src/features/projectsV2/ProjectsMap/MapFeatureExplorer/MapSettings.tsx
  src/features/projectsV2/ProjectsMap/MapFeatureExplorer/MobileMapSettingsLayout.module.scss
  src/features/projectsV2/ProjectsMap/MapFeatureExplorer/MobileMapSettingsLayout.tsx
  src/features/projectsV2/ProjectsMap/MapFeatureExplorer/YearSlider/CustomSlider.tsx
  src/features/projectsV2/ProjectsMap/MapFeatureExplorer/YearSlider/YearSlider.module.scss
  src/features/projectsV2/ProjectsMap/MapFeatureExplorer/YearSlider/index.tsx
  src/features/projectsV2/ProjectsMap/MapFeatureExplorer/index.tsx
  src/features/projectsV2/ProjectsMap/MapFeatureExplorer/microComponents/LayerInfoPopupContent.tsx
  src/features/projectsV2/ProjectsMap/MapFeatureExplorer/microComponents/MapSettingsSection.tsx
  src/features/projectsV2/ProjectsMap/MapFeatureExplorer/microComponents/SingleLayerOption.tsx
  src/features/projectsV2/ProjectsMap/index.tsx
  src/features/projectsV2/ProjectsMap/stories/MapFeatureExplorer.stories.tsx
  src/features/projectsV2/ProjectsMapContext.tsx
  src/utils/mapsV2/mapSettings.config.ts
  src/utils/mapsV2/useFetchLayers.ts
Labels: PR: reviewed-approved
