Repository Plant-for-the-Planet-org/planet-webapp, pull requests merged in 2025-09, with the labels that each got.

#2678 Remove null subtitle prop from DashboardView across app
  src/features/common/Layout/DashboardView/index.tsx
  src/features/user/RegisterTrees/index.tsx
  src/features/user/Settings/DeleteProfile/index.tsx
  src/features/user/Settings/EditProfile/index.tsx
  src/features/user/TreeMapper/Analytics/index.tsx
  src/features/user/TreeMapper/MySpecies/index.tsx
Labels: PR: reviewed-approved

#2682 Fix division by zero in area and density calculations
  src/features/projects/components/Intervention/InterventionDetails.tsx
  src/features/projects/components/maps/Interventions.tsx
  src/features/projectsV2/ProjectDetails/components/MultiTreeInfo.tsx
  src/features/projectsV2/ProjectsMap/ProjectSiteDropDown/index.tsx
  src/features/projectsV2/ProjectsMap/microComponents/InterventionLayers.tsx
  src/features/user/TreeMapper/Analytics/components/Map/index.tsx
  src/features/user/TreeMapper/components/Map.tsx
  src/features/user/TreeMapper/components/TreemapperIntervention.tsx
Labels: PR: reviewed-approved

#2687 Refactor site area calculation in SiteDropdown
  src/features/projectsV2/ProjectsMap/ProjectSiteDropDown/index.tsx
Labels: PR: unreviewed

#2691 Update @planet-sdk/common to v0.2.4 and refactor imports
  package-lock.json
  package.json
  pages/sites/[slug]/[locale]/projects-archive/[p].tsx
  src/features/common/CarouselSlider/index.tsx
  src/features/common/Layout/ErrorHandlingContext.tsx
  src/features/common/Layout/ProjectPropsContext.tsx
  src/features/common/Layout/UserLayout/NavLink.tsx
  src/features/common/types/ProjectPropsContextInterface.ts
  src/features/common/types/intervention.d.ts
  src/features/common/types/map.d.ts
  src/features/projects/components/Intervention/InterventionDetails.tsx
  src/features/projects/components/ProjectsMap.tsx
  src/features/projects/components/maps/Interventions.tsx
  src/features/projectsV2/ProjectDetails/components/MultiTreeInfo.tsx
  src/features/projectsV2/ProjectDetails/components/OtherInterventionInfo.tsx
  src/features/projectsV2/ProjectDetails/components/SingleTreeInfo.tsx
  src/features/projectsV2/ProjectDetails/components/microComponents/PlantInfoCard.tsx
  src/features/projectsV2/ProjectDetails/components/microComponents/SampleTreesInfo.tsx
  src/features/projectsV2/ProjectDetails/components/microComponents/SingleTreeInfoHeader.tsx
  src/features/projectsV2/ProjectDetails/components/microComponents/SpeciesPlanted.tsx
  src/features/projectsV2/ProjectDetails/index.tsx
  src/features/projectsV2/ProjectsContext.tsx
  src/features/projectsV2/ProjectsMap/ProjectSiteDropDown/ProjectSiteList.tsx
  src/features/projectsV2/ProjectsMap/ProjectSiteDropDown/index.tsx
  src/features/projectsV2/ProjectsMap/index.tsx
  src/features/projectsV2/ProjectsMap/microComponents/InterventionLayers.tsx
  src/features/projectsV2/ProjectsMap/stories/ProjectSiteDropdown.stories.tsx
  src/features/user/Account/components/RecurrencyRecord.tsx
  src/features/user/TreeMapper/Import/components/PlantingLocation.tsx
  src/features/user/TreeMapper/Import/components/ReviewSubmit.tsx
  src/features/user/TreeMapper/Import/components/SampleTreeCard.tsx
  src/features/user/TreeMapper/Import/components/SampleTrees.tsx
  src/features/user/TreeMapper/Import/index.tsx
  src/features/user/TreeMapper/MySpecies/MySpeciesForm.tsx
  src/features/user/TreeMapper/MySpecies/SpeciesAutoComplete.tsx
  src/features/user/TreeMapper/Treemapper.d.ts
  src/features/user/TreeMapper/components/InterventionPage.tsx
  src/features/user/TreeMapper/components/Map.tsx
  src/features/user/TreeMapper/components/TreeMapperList.tsx
  src/features/user/TreeMapper/components/TreemapperIntervention.tsx
  src/features/user/TreeMapper/index.tsx
  src/utils/constants/intervention.ts
  src/utils/maps/zoomToPolygonIntervention.ts
  src/utils/projectV2.ts
Labels: PR: unreviewed, PR: reviewed-approved

#2694 refactor: replace hardcoded colors with design system colors
  src/features/projectsV2/ProjectsMap/FirePopup/index.tsx
  src/features/projectsV2/ProjectsMap/SiteMapLayerControls/SiteLayerOptions.tsx
  src/features/projectsV2/ProjectsMap/TimeTravel/index.tsx
  src/features/projectsV2/ProjectsMap/stories/SingleMapTab.stories.tsx
  src/features/projectsV2/ProjectsMap/stories/SiteMapLayerControls.stories.tsx
Labels: PR: reviewed-approved

#2696 Update ProjectSiteDropdown to handle single site display
  src/features/projectsV2/ProjectsMap/MapControls.tsx
  src/features/projectsV2/ProjectsMap/ProjectSiteDropDown/SiteDropdown.module.scss
  src/features/projectsV2/ProjectsMap/ProjectSiteDropDown/index.tsx
Labels: PR: unreviewed
