Repository Plant-for-the-Planet-org/planet-webapp, pull requests merged in 2025-03, with the labels that each got.

#2414 [Snyk] Upgrade papaparse from 5.5.1 to 5.5.2
  package-lock.json
  package.json
Labels: dependencies, PR: reviewed-approved

#2415 [Snyk] Upgrade react-insta-stories from 2.7.0 to 2.8.0
  package-lock.json
  package.json
Labels: dependencies, PR: reviewed-approved

#2431 Make LayerInfoPopupContent translatable
  public/static/locales/en/maps.json
  src/features/projectsV2/ProjectsMap/MapFeatureExplorer/microComponents/LayerInfoPopupContent.tsx
  src/features/projectsV2/ProjectsMap/MapFeatureExplorer/microComponents/SingleLayerOption.tsx
  src/utils/mapsV2/mapSettings.config.ts
Labels: PR: unreviewed

#2420 Improve middleware performance in multi-tenant setup
  src/utils/multiTenancy/helpers.ts
Labels: PR: reviewed-approved

#2407 Add prefetching support for external links in WebappButton component
  src/features/common/WebappButton/index.tsx
  src/features/projectsV2/ProjectSnippet/microComponents/ProjectInfoSection.tsx
  src/utils/prefetchManager.ts
Labels: PR: reviewed-approved

#2433 Add cSpell configuration and fix spelling issues in translation files
  cspell.json
  public/static/locales/cs/giftfunds.json
  public/static/locales/cs/managePayouts.json
  public/static/locales/de/giftfunds.json
  public/static/locales/de/managePayouts.json
  public/static/locales/en/common.json
  public/static/locales/en/donate.json
  public/static/locales/en/donationLink.json
  public/static/locales/en/editProfile.json
  public/static/locales/en/giftfunds.json
  public/static/locales/en/managePayouts.json
  public/static/locales/es/giftfunds.json
  public/static/locales/es/managePayouts.json
  public/static/locales/fr/giftfunds.json
  public/static/locales/fr/managePayouts.json
  public/static/locales/it/giftfunds.json
  public/static/locales/it/managePayouts.json
  public/static/locales/pt-BR/giftfunds.json
  public/static/locales/pt-BR/managePayouts.json
  src/features/user/GiftFunds/GiftFundDetails.tsx
  src/features/user/GiftFunds/index.tsx
  src/features/user/ManagePayouts/screens/EditBankAccount.tsx
  src/features/user/Widget/DonationLink/index.tsx
Labels: PR: reviewed-approved

#2435 Corrects typos in translation files
  cspell.json
  pages/sites/[slug]/[locale]/profile/planetcash/index.tsx
  pages/sites/[slug]/[locale]/profile/planetcash/new.tsx
  pages/sites/[slug]/[locale]/profile/planetcash/transactions.tsx
  public/static/locales/cs/manageProjects.json
  public/static/locales/cs/me.json
  public/static/locales/cs/planetcash.json
  public/static/locales/de/manageProjects.json
  public/static/locales/de/me.json
  public/static/locales/de/planetcash.json
  public/static/locales/en/manageProjects.json
  public/static/locales/en/me.json
  public/static/locales/en/planet.json
  public/static/locales/en/planetcash.json
  public/static/locales/es/manageProjects.json
  public/static/locales/es/me.json
  public/static/locales/es/planetcash.json
  public/static/locales/fr/manageProjects.json
  public/static/locales/fr/me.json
  public/static/locales/fr/planetcash.json
  public/static/locales/it/manageProjects.json
  public/static/locales/it/me.json
  public/static/locales/it/planetcash.json
  public/static/locales/pt-BR/manageProjects.json
  public/static/locales/pt-BR/me.json
  public/static/locales/pt-BR/planetcash.json
  src/features/common/Layout/UserLayout/UserLayout.tsx
  src/features/user/ManageProjects/components/ProjectSites.tsx
  src/features/user/ManageProjects/index.tsx
  src/features/user/PlanetCash/components/AccountDetails.tsx
  src/features/user/PlanetCash/components/CreateAccountForm.tsx
  src/features/user/PlanetCash/components/NoPlanetCashAccount.tsx
  src/features/user/PlanetCash/index.tsx
  src/features/user/PlanetCash/screens/CreateAccount.tsx
Labels: PR: reviewed-approved

#2457 Include country in fetchRegistrations query
  src/server/procedures/myForest/contributions.ts
Labels: PR: unreviewed

#2458 Fix: simplify and correct showContentContainer conditional logic
  src/features/common/Layout/ProjectsLayout/index.tsx
Labels: PR: reviewed-approved

#2439 Feature/donation filter
  public/assets/images/icons/projectV2/DollarIcon.tsx
  public/static/locales/en/allProjects.json
  src/features/projectsV2/ProjectList/index.tsx
  src/features/projectsV2/ProjectListControls/ProjectListControlForMobile.tsx
  src/features/projectsV2/ProjectListControls/index.tsx
  src/features/projectsV2/ProjectListControls/microComponents/ClassificationDropDown.tsx
  src/features/projectsV2/ProjectListControls/styles/ProjectListControls.module.scss
  src/features/projectsV2/ProjectsContext.tsx
  src/features/projectsV2/ProjectsMap/MapControls.tsx
  src/features/projectsV2/ProjectsSection.tsx
Labels: PR: reviewed-approved

#2465 Release: donation filter + donation receipt warning when tin is required
  public/assets/images/icons/projectV2/DollarIcon.tsx
  public/static/locales/de/allProjects.json
  public/static/locales/en/allProjects.json
  public/static/locales/en/donationReceipt.json
  src/features/projectsV2/ProjectList/index.tsx
  src/features/projectsV2/ProjectListControls/ProjectListControlForMobile.tsx
  src/features/projectsV2/ProjectListControls/index.tsx
  src/features/projectsV2/ProjectListControls/microComponents/ClassificationDropDown.tsx
  src/features/projectsV2/ProjectListControls/styles/ProjectListControls.module.scss
  src/features/projectsV2/ProjectsContext.tsx
  src/features/projectsV2/ProjectsMap/MapControls.tsx
  src/features/projectsV2/ProjectsSection.tsx
  src/features/user/DonationReceipt/DonationReceiptWrapper.tsx
  src/features/user/DonationReceipt/microComponents/DonationReceipt.tsx
  src/features/user/DonationReceipt/microComponents/ReceiptDataSection.tsx
Labels: PR: unreviewed

#2444 [Snyk] Upgrade swiper from 11.2.1 to 11.2.4
  package-lock.json
  package.json
Labels: dependencies, PR: reviewed-approved

#2445 [Snyk] Upgrade next-intl from 3.26.3 to 3.26.5
  package-lock.json
  package.json
Labels: dependencies, PR: reviewed-approved

#2470 Remove unused styles from RedeemModal
  src/features/common/RedeemCode/style/RedeemModal.module.scss
Labels: PR: reviewed-approved

#2473 fix: restrict project fetch when registering a tree for non-TPO users
  src/features/user/RegisterTrees/RegisterTreesWidget.tsx
Labels: PR: reviewed-approved
