Repository Plant-for-the-Planet-org/planet-webapp, pull requests merged in 2025-04, with the labels that each got.

#2455 Feature/api
  cspell.json
  package.json
  pages/sites/[slug]/[locale]/all.tsx
  src/features/projectsV2/ProjectDetails/index.tsx
  src/features/projectsV2/ProjectsContext.tsx
  src/features/user/DonationReceipt/DonationReceiptUnauthenticated.tsx
  src/features/user/DonationReceipt/DonationReceiptWrapper.tsx
  src/features/user/DonationReceipt/DonationReceipts.tsx
  src/features/user/DonationReceipt/DonorContactManagement.tsx
  src/hooks/useApi.ts
  src/hooks/useServerApi.ts
  src/utils/apiRequests/apiClient.ts
Labels: PR: unreviewed

#2476 [Snyk] Upgrade sass from 1.83.4 to 1.85.1
  package-lock.json
  package.json
Labels: dependencies, PR: reviewed-approved

#2466 Feature/use server api hook
  pages/sites/[slug]/[locale]/claim/[type]/[code].tsx
  src/features/user/CompleteSignup/index.tsx
  src/features/user/Settings/ApiKey/ApiKeyForm.tsx
  src/features/user/Settings/DeleteProfile/DeleteProfileForm.tsx
  src/hooks/useApi.ts
Labels: PR: reviewed-approved

#2477 Feature/use api hook3
  pages/sites/[slug]/[locale]/profile/projects/[id].tsx
  src/features/common/types/project.d.ts
  src/features/user/ManagePayouts/components/BankDetailsForm.tsx
  src/features/user/ManagePayouts/index.tsx
  src/features/user/ManagePayouts/screens/AddBankAccount.tsx
  src/features/user/ManagePayouts/screens/EditBankAccount.tsx
  src/features/user/ManagePayouts/screens/PayoutScheduleForm.tsx
  src/features/user/ManageProjects/ProjectsContainer.tsx
  src/features/user/ManageProjects/components/BasicDetails.tsx
  src/features/user/ManageProjects/components/DetailedAnalysis.tsx
  src/features/user/ManageProjects/components/ProjectCertificates.tsx
  src/features/user/ManageProjects/components/ProjectMedia.tsx
  src/features/user/ManageProjects/components/ProjectSites.tsx
  src/features/user/ManageProjects/components/ProjectSpending.tsx
  src/features/user/ManageProjects/index.tsx
Labels: PR: unreviewed

#2474 Feature/use api hook2
  pages/sites/[slug]/[locale]/profile/bulk-codes/[method]/[id].tsx
  pages/sites/[slug]/[locale]/profile/recurrency.tsx
  src/features/common/types/map.d.ts
  src/features/user/BulkCodes/components/ProjectSelector.tsx
  src/features/user/BulkCodes/forms/IssueCodesForm.tsx
  src/features/user/BulkCodes/index.tsx
  src/features/user/RegisterTrees/RegisterTreesWidget.tsx
Labels: PR: unreviewed

#2482 Update mangroves landing page and fix navigation bug
  pages/sites/[slug]/[locale]/mangroves.tsx
  src/tenants/salesforce/Mangroves/components/ContentSection.tsx
  src/tenants/salesforce/Mangroves/components/ProjectGrid.tsx
Labels: PR: reviewed-approved

#2481 Feature/use api hook6
  src/features/user/PlanetCash/components/CreateAccountForm.tsx
  src/features/user/PlanetCash/screens/Transactions.tsx
  src/features/user/Settings/EditProfile/AddressManagement/AddAddress.tsx
  src/features/user/Settings/EditProfile/AddressManagement/DeleteAddress.tsx
  src/features/user/Settings/EditProfile/AddressManagement/EditAddress.tsx
  src/features/user/Settings/EditProfile/AddressManagement/UnsetBillingAddress.tsx
  src/features/user/Settings/EditProfile/AddressManagement/UpdateAddressType.tsx
  src/features/user/Settings/EditProfile/AddressManagement/index.tsx
  src/features/user/Settings/EditProfile/AddressManagement/microComponents/AddressForm.tsx
Labels: PR: reviewed-approved

#2486 Release Maintainance (e.g. migrating API handling to useApi hook)
  cspell.json
  package-lock.json
  package.json
  pages/sites/[slug]/[locale]/all.tsx
  pages/sites/[slug]/[locale]/claim/[type]/[code].tsx
  pages/sites/[slug]/[locale]/profile/bulk-codes/[method]/[id].tsx
  pages/sites/[slug]/[locale]/profile/history.tsx
  pages/sites/[slug]/[locale]/profile/projects/[id].tsx
  pages/sites/[slug]/[locale]/profile/recurrency.tsx
  src/features/common/types/map.d.ts
  src/features/common/types/project.d.ts
  src/features/projectsV2/ProjectDetails/index.tsx
  src/features/projectsV2/ProjectsContext.tsx
  src/features/user/BulkCodes/components/ProjectSelector.tsx
  src/features/user/BulkCodes/forms/IssueCodesForm.tsx
  src/features/user/BulkCodes/index.tsx
  src/features/user/CompleteSignup/index.tsx
  src/features/user/DonationReceipt/DonationReceiptUnauthenticated.tsx
  src/features/user/DonationReceipt/DonationReceiptWrapper.tsx
  src/features/user/DonationReceipt/DonationReceipts.tsx
  src/features/user/DonationReceipt/DonorContactManagement.tsx
  src/features/user/ManagePayouts/components/BankDetailsForm.tsx
  src/features/user/ManagePayouts/index.tsx
  src/features/user/ManagePayouts/screens/AddBankAccount.tsx
  src/features/user/ManagePayouts/screens/EditBankAccount.tsx
  src/features/user/ManagePayouts/screens/PayoutScheduleForm.tsx
  src/features/user/ManageProjects/ProjectsContainer.tsx
  src/features/user/ManageProjects/components/BasicDetails.tsx
  src/features/user/ManageProjects/components/DetailedAnalysis.tsx
  src/features/user/ManageProjects/components/ProjectCertificates.tsx
  src/features/user/ManageProjects/components/ProjectMedia.tsx
  src/features/user/ManageProjects/components/ProjectSites.tsx
  src/features/user/ManageProjects/components/ProjectSpending.tsx
  src/features/user/ManageProjects/index.tsx
  src/features/user/PlanetCash/components/CreateAccountForm.tsx
  src/features/user/PlanetCash/screens/Transactions.tsx
  src/features/user/RegisterTrees/RegisterTreesWidget.tsx
  src/features/user/Settings/ApiKey/ApiKeyForm.tsx
  src/features/user/Settings/DeleteProfile/DeleteProfileForm.tsx
  src/features/user/Settings/EditProfile/AddressManagement/AddAddress.tsx
  src/features/user/Settings/EditProfile/AddressManagement/DeleteAddress.tsx
  src/features/user/Settings/EditProfile/AddressManagement/EditAddress.tsx
  src/features/user/Settings/EditProfile/AddressManagement/UnsetBillingAddress.tsx
  src/features/user/Settings/EditProfile/AddressManagement/UpdateAddressType.tsx
  src/features/user/Settings/EditProfile/AddressManagement/index.tsx
  src/features/user/Settings/EditProfile/AddressManagement/microComponents/AddressForm.tsx
  src/features/user/Settings/EditProfile/EditProfileForm.tsx
  src/features/user/Widget/DonationLink/index.tsx
  src/hooks/useApi.ts
  src/hooks/useServerApi.ts
  src/utils/apiRequests/apiClient.ts
Labels: PR: reviewed-approved

#2487 Add URL parameters for project filters
  src/features/projectsV2/ProjectsContext.tsx
  src/features/projectsV2/ProjectsSection.tsx
  src/utils/projectV2.ts
Labels: PR: reviewed-approved

#2488 Use Api Hook 7
  pages/_app.tsx
  pages/sites/[slug]/[locale]/all.tsx
  pages/sites/[slug]/[locale]/home.tsx
  pages/sites/[slug]/[locale]/projects-archive/[p].tsx
  pages/sites/[slug]/[locale]/projects-archive/index.tsx
  src/features/common/Layout/CurrencyContext.tsx
  src/features/projects/screens/Projects.tsx
  src/features/user/Profile/TpoProjects/index.tsx
  src/tenants/salesforce/VTOCampaign2023/components/ProjectGrid.tsx
  src/tenants/salesforce/VTOCampaign2024/components/ProjectGrid.tsx
Labels: PR: unreviewed

#2491 Feature/use api hook 10
  src/features/user/PlanetCash/index.tsx
  src/features/user/TreeMapper/Import/components/PlantingLocation.tsx
Labels: PR: unreviewed

#2492 Feature/use api hook9
  src/features/user/Profile/ProfileCard/RedeemModal/index.tsx
  src/features/user/RegisterTrees/RegisterTrees/UploadImages.tsx
  src/features/user/TreeMapper/Import/components/PlantingLocation.tsx
  src/features/user/TreeMapper/Import/components/SampleTrees.tsx
  src/features/user/TreeMapper/MySpecies/SpeciesAutoComplete.tsx
  src/tenants/planet/LeaderBoard/components/Score.tsx
Labels: PR: reviewed-approved

#2479 Feature/use api hook5
  pages/sites/[slug]/[locale]/profile/redeem/[code].tsx
  pages/sites/[slug]/[locale]/s/[id].tsx
  pages/sites/[slug]/[locale]/t/[profile].tsx
  src/features/projectsV2/ProjectsMap/microComponents/FireLocations.tsx
  src/features/user/Account/components/DownloadCodes.tsx
  src/features/user/TreeMapper/Analytics/index.tsx
  src/features/user/TreeMapper/Import/index.tsx
  src/features/user/TreeMapper/MySpecies/MySpeciesForm.tsx
  src/features/user/TreeMapper/index.tsx
  src/tenants/salesforce/Mangroves/components/ProjectGrid.tsx
  src/tenants/salesforce/OceanforceCampaign/components/ContentSection.tsx
  src/tenants/salesforce/VTOCampaign2025/components/ProjectGrid.tsx
Labels: PR: reviewed-changes-requested

#2490 Feature/use api hook8
  src/features/common/types/payments.d.ts
  src/features/user/Account/CancelModal.tsx
  src/features/user/Account/EditModal.tsx
  src/features/user/Account/PauseModal.tsx
  src/features/user/Account/ReactivateModal.tsx
  src/features/user/Profile/ForestProgress/TargetsModal.tsx
  src/features/user/RegisterTrees/RegisterTrees/SingleContribution.tsx
  src/features/user/RegisterTrees/RegisterTrees/UploadImages.tsx
  src/features/user/RegisterTrees/RegisterTreesWidget.tsx
  src/features/user/Settings/ImpersonateUser/SupportPin.tsx
  src/features/user/Widget/EmbedModal.tsx
  src/hooks/useApi.ts
Labels: PR: reviewed-approved

#2472 Corrects incorrect component/file names in webapp
  src/features/common/TreeCounter/TreeCounter.tsx
  src/tenants/common/Home/index.tsx
  src/tenants/planet/LeaderBoard/index.tsx
  src/tenants/salesforce/Home/components/Landing.tsx
  src/tenants/salesforce/Mangroves/components/Landing.tsx
  src/tenants/salesforce/OceanforceCampaign/components/Landing.tsx
  src/tenants/salesforce/TreeCounter/index.tsx
  src/tenants/salesforce/VTOCampaign2023/components/Landing.tsx
  src/tenants/salesforce/VTOCampaign2024/components/Landing.tsx
  src/tenants/salesforce/VTOCampaign2025/components/Landing.tsx
  src/tenants/stern/Home/index.tsx
Labels: PR: unreviewed

#2498 Refetch projects data on currency change
  src/features/projectsV2/ProjectsContext.tsx
Labels: PR: reviewed-approved
