Repository Plant-for-the-Planet-org/planet-webapp, pull requests merged in 2025-01, with the labels that each got.

#2349 Fix bug preventing tab switching in project list
  src/features/projectsV2/ProjectListControls/index.tsx
Labels: PR: reviewed-approved

#2342 feat: add GetStaticPaths type to enforce type safety in getStaticPath…
  pages/sites/[slug]/[locale]/[p].tsx
  pages/sites/[slug]/[locale]/all.tsx
  pages/sites/[slug]/[locale]/claim/[type]/[code].tsx
  pages/sites/[slug]/[locale]/complete-signup.tsx
  pages/sites/[slug]/[locale]/home.tsx
  pages/sites/[slug]/[locale]/index.tsx
  pages/sites/[slug]/[locale]/login.tsx
  pages/sites/[slug]/[locale]/mangrove-challenge.tsx
  pages/sites/[slug]/[locale]/mangroves.tsx
  pages/sites/[slug]/[locale]/profile/api-key.tsx
  pages/sites/[slug]/[locale]/profile/bulk-codes/[method]/[id].tsx
  pages/sites/[slug]/[locale]/profile/bulk-codes/[method]/index.tsx
  pages/sites/[slug]/[locale]/profile/bulk-codes/index.tsx
  pages/sites/[slug]/[locale]/profile/delete-account.tsx
  pages/sites/[slug]/[locale]/profile/donation-link.tsx
  pages/sites/[slug]/[locale]/profile/edit.tsx
  pages/sites/[slug]/[locale]/profile/giftfund/index.tsx
  pages/sites/[slug]/[locale]/profile/history.tsx
  pages/sites/[slug]/[locale]/profile/impersonate-user.tsx
  pages/sites/[slug]/[locale]/profile/index.tsx
  pages/sites/[slug]/[locale]/profile/payouts/add-bank-details.tsx
  pages/sites/[slug]/[locale]/profile/payouts/edit-bank-details/[id].tsx
  pages/sites/[slug]/[locale]/profile/payouts/index.tsx
  pages/sites/[slug]/[locale]/profile/payouts/schedule.tsx
  pages/sites/[slug]/[locale]/profile/planetcash/index.tsx
  pages/sites/[slug]/[locale]/profile/planetcash/new.tsx
  pages/sites/[slug]/[locale]/profile/planetcash/transactions.tsx
  pages/sites/[slug]/[locale]/profile/projects/[id].tsx
  pages/sites/[slug]/[locale]/profile/projects/index.tsx
  pages/sites/[slug]/[locale]/profile/projects/new-project.tsx
  pages/sites/[slug]/[locale]/profile/recurrency.tsx
  pages/sites/[slug]/[locale]/profile/redeem/[code].tsx
  pages/sites/[slug]/[locale]/profile/register-trees.tsx
  pages/sites/[slug]/[locale]/profile/treemapper/data-explorer.tsx
  pages/sites/[slug]/[locale]/profile/treemapper/import.tsx
  pages/sites/[slug]/[locale]/profile/treemapper/index.tsx
  pages/sites/[slug]/[locale]/profile/treemapper/my-species.tsx
  pages/sites/[slug]/[locale]/profile/widgets.tsx
  pages/sites/[slug]/[locale]/projects-archive/[p].tsx
  pages/sites/[slug]/[locale]/projects-archive/index.tsx
  pages/sites/[slug]/[locale]/s/[id].tsx
  pages/sites/[slug]/[locale]/t/[profile].tsx
  pages/sites/[slug]/[locale]/verify-email.tsx
  pages/sites/[slug]/[locale]/vto-fitness-challenge-2023.tsx
  pages/sites/[slug]/[locale]/vto-fitness-challenge.tsx
Labels: PR: reviewed-approved

#2345 refactor: update header text on the public profile sdg section.
  public/static/locales/en/profile.json
  src/features/common/CarouselSlider/index.tsx
  src/features/user/Profile/InfoAndCTA/SDGCardList/index.tsx
Labels: PR: reviewed-approved

#2341 fix: trigger contributions refetch after redeeming code
  src/features/common/Layout/MyForestContext.tsx
  src/features/user/Profile/ProfileCard/RedeemModal/index.tsx
Labels: PR: reviewed-approved

#2360 [Snyk] Security upgrade next from 13.5.7 to 13.5.8
  package-lock.json
  package.json
Labels: dependencies, PR: reviewed-approved

#2359 Icon changes
  public/assets/images/icons/headerIcons/DefaultProfileImageIcon.tsx
  public/assets/images/icons/projectV2/PointMarkerIconsSymbol.tsx
  src/features/projectsV2/ProjectListControls/microComponents/ClassificationDropDown.tsx
  src/features/projectsV2/ProjectListControls/styles/ProjectListControls.module.scss
  src/features/user/Profile/ProfileCard/index.tsx
  src/features/user/Settings/EditProfile/EditProfile.module.scss
  src/features/user/Settings/EditProfile/EditProfileForm.tsx
Labels: PR: reviewed-approved

#2366 Release Map Key and Profile Icon
  public/assets/images/icons/headerIcons/DefaultProfileImageIcon.tsx
  public/assets/images/icons/projectV2/PointMarkerIconsSymbol.tsx
  src/features/projectsV2/ProjectListControls/microComponents/ClassificationDropDown.tsx
  src/features/projectsV2/ProjectListControls/styles/ProjectListControls.module.scss
  src/features/user/Profile/ProfileCard/index.tsx
  src/features/user/Settings/EditProfile/EditProfile.module.scss
  src/features/user/Settings/EditProfile/EditProfileForm.tsx
Labels: PR: reviewed-approved

#2370 Hotfix/intervention-filter
  src/features/projectsV2/ProjectsMap/InterventionDropDown/InterventionList.module.scss
  src/features/projectsV2/ProjectsMap/InterventionDropDown/InterventionList.tsx
  src/features/projectsV2/ProjectsMap/InterventionDropDown/index.tsx
  src/features/projectsV2/ProjectsMap/MapControls.tsx
Labels: PR: reviewed-approved

#2369 Migrate database connection from MySQL to PostgreSQL (Data explorer)
  package-lock.json
  package.json
  pages/api/data-explorer/export.ts
  pages/api/data-explorer/map/distinct-species/[projectId].ts
  pages/api/data-explorer/map/plant-location/[plantLocationId].ts
  pages/api/data-explorer/map/plant-location/index.ts
  pages/api/data-explorer/map/sites/[projectId].ts
  pages/api/data-explorer/species-planted.ts
  pages/api/data-explorer/total-species-planted.ts
  pages/api/data-explorer/total-trees-planted.ts
  pages/api/data-explorer/trees-planted.ts
  src/features/common/types/dataExplorer.d.ts
  src/features/user/TreeMapper/Analytics/components/TreePlanted/index.tsx
  src/utils/connectDB.ts
Labels: PR: unreviewed

#2364 Migrate database schema and trpc procedures to PostgreSQL
  package-lock.json
  package.json
  pages/api/data-explorer/export.ts
  pages/api/data-explorer/map/distinct-species/[projectId].ts
  pages/api/data-explorer/map/plant-location/[plantLocationId].ts
  pages/api/data-explorer/map/plant-location/index.ts
  pages/api/data-explorer/map/sites/[projectId].ts
  pages/api/data-explorer/species-planted.ts
  pages/api/data-explorer/total-species-planted.ts
  pages/api/data-explorer/total-trees-planted.ts
  pages/api/data-explorer/trees-planted.ts
  prisma/schema.prisma
  src/features/common/types/dataExplorer.d.ts
  src/features/user/TreeMapper/Analytics/components/TreePlanted/index.tsx
  src/server/procedures/myForest/contributions.ts
  src/server/procedures/myForest/leaderboard.ts
  src/server/procedures/myForest/projectList.ts
  src/server/utils/fetchProfileGroupData.ts
  src/utils/connectDB.ts
Labels: PR: unreviewed

#2376 Improve user widget rendering and handle null cases
  pages/sites/[slug]/[locale]/profile/widgets.tsx
Labels: PR: reviewed-approved

#2382 [Snyk] Upgrade zod from 3.23.8 to 3.24.1
  package-lock.json
  package.json
Labels: dependencies, PR: reviewed-approved

#2383 [Snyk] Upgrade @mui/icons-material from 5.16.8 to 5.16.13
  package-lock.json
  package.json
Labels: dependencies, PR: reviewed-approved

#2385 Release Dependency PRs
  package-lock.json
  package.json
Labels: PR: reviewed-approved

#2356 Integrated fires API
  .gitignore
  public/assets/images/icons/FireIcon.tsx
  public/assets/images/icons/FirePopupIcon.tsx
  public/static/locales/de/projectDetails.json
  public/static/locales/en/projectDetails.json
  src/features/common/types/fireLocation.d.ts
  src/features/projectsV2/ProjectsMap/FirePopup/FirePopup.module.scss
  src/features/projectsV2/ProjectsMap/FirePopup/FirePopup.stories.tsx
  src/features/projectsV2/ProjectsMap/FirePopup/index.tsx
  src/features/projectsV2/ProjectsMap/SingleProjectView.tsx
  src/features/projectsV2/ProjectsMap/microComponents/FeatureFlag.tsx
  src/features/projectsV2/ProjectsMap/microComponents/FireLocations.tsx
  src/temp/FirePopup/FirePopup.module.scss
  src/temp/FirePopup/index.tsx
  src/utils/projectV2.ts
Labels: PR: reviewed-changes-requested

#2329 Feature/project-time-travel
  package-lock.json
  package.json
  public/assets/images/icons/FieldDataIcon.tsx
  public/assets/images/icons/projectV2/CalendarIcon.tsx
  public/assets/images/icons/projectV2/DropdownDownArrow.tsx
  public/assets/images/icons/projectV2/DropdownUpArrow.tsx
  public/data/maps/time-travel.json
  public/static/locales/en/projectDetails.json
  src/features/common/Layout/ProjectPropsContext.tsx
  src/features/common/types/maplibre-gl-compare.d.ts
  src/features/projects/components/maps/Project.tsx
  src/features/projectsV2/ProjectDetails/index.tsx
  src/features/projectsV2/ProjectsMap/InterventionDropDown/index.tsx
  src/features/projectsV2/ProjectsMap/MapControls.tsx
  src/features/projectsV2/ProjectsMap/ProjectMapTabs/ProjectMapTabs.module.scss
  src/features/projectsV2/ProjectsMap/ProjectMapTabs/SingleTab.tsx
  src/features/projectsV2/ProjectsMap/ProjectMapTabs/index.tsx
  src/features/projectsV2/ProjectsMap/ProjectSiteDropDown/SiteDropdown.module.scss
  src/features/projectsV2/ProjectsMap/ProjectSiteDropDown/index.tsx
  src/features/projectsV2/ProjectsMap/ProjectsMap.module.scss
  src/features/projectsV2/ProjectsMap/SingleProjectView.tsx
  src/features/projectsV2/ProjectsMap/TimeTravel/TimeTravel.module.scss
  src/features/projectsV2/ProjectsMap/TimeTravel/index.tsx
  src/features/projectsV2/ProjectsMap/index.tsx
  src/features/projectsV2/ProjectsMap/stories/SingleMapTab.stories.tsx
  src/features/projectsV2/ProjectsMap/stories/Tabs.stories.tsx
  src/features/projectsV2/ProjectsMap/stories/TimeTravelDropdown.stories.tsx
  src/features/projectsV2/ProjectsMapContext.tsx
  src/features/projectsV2/TimeTravelDropdown/TimeTravelDropdown.module.scss
  src/features/projectsV2/TimeTravelDropdown/index.tsx
  src/temp/ProjectMapTabs/ProjectMapTabs.module.scss
  src/temp/ProjectMapTabs/Tabs.tsx
  src/temp/TimeTravelDropdown/Dropdown.module.scss
  src/temp/TimeTravelDropdown/index.tsx
  src/temp/icons/FieldDataIcon.tsx
  src/theme/themeProperties.ts
  src/utils/mapsV2/timeTravel.ts
Labels: PR: unreviewed

#2365 refactor: refactor satellite view logic in useEffect
  src/features/projectsV2/ProjectsMap/SingleProjectView.tsx
Labels: PR: reviewed-approved

#2386 intervention condition added
  src/features/projectsV2/ProjectsMap/microComponents/PlantLocations.tsx
Labels: PR: reviewed-approved
